Repository gravitee-io/gravitee-access-management, pull requests merged in 2023-07, with the labels that each got.

#2728 fix: multi tab session expired
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CSRFHandlerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSession.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-master

#2717 fix(perf): improve JDBC implementation performance
  gravitee-am-common/src/main/java/io/gravitee/am/common/event/Event.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/audit/impl/AuditReporterManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/oauth2/impl/IntrospectionTokenServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/authdevice/notifier/impl/AuthenticationDeviceNotifierManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/resource/impl/ResourceManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/AuthenticationRequestServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequestResolver.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/CompositeTokenGranter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/par/impl/PushedAuthorizationRequestServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/DynamicClientAccessEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/jwe/impl/JWEServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditReporterManagerImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateServiceProxyImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/plugins/NotifierPluginService.java
  gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/audit/JdbcAuditReporter.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAccessTokenRepository.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/OrganizationUserServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/impl/AuditReporterVerticle.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/OrganizationUserServiceTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
Labels: apply-on-master

#2753 chore: update management-ui files
  docker/management-ui/Dockerfile
  docker/management-ui/Dockerfile-dev
  docker/management-ui/Dockerfile-nightly
  docker/management-ui/config/conf.d/constants.json.toml
  docker/management-ui/config/conf.d/default.conf.toml
  docker/management-ui/config/constants.json
  docker/management-ui/config/default.conf
  docker/management-ui/config/templates/constants.json.tmpl
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#2761 Stop creating EE tags for docker images
  .circleci/workflows.yml
Labels: apply-on-master

#2754 fix: use correct entity wrapper for patch username
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UserResource.java
Labels: apply-on-master, apply-on-4-0-x

#2767 fix: DOS vuln on org.json:json due to infobip-api-java-client
  gravitee-am-resource/gravitee-am-resource-infobip/pom.xml
  pom.xml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x

#2775 fix: use domain i18n dictionaries for emails
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceImplTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/EmailServiceImplTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/EmailServiceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/EmailService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/CompositeDictionaryProvider.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/DomainBasedDictionaryProvider.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/DynamicDictionaryProvider.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/GraviteeMessageResolver.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/ThreadLocalDomainDictionaryProvider.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EmailServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/CompositeDictionaryProviderTest.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-master, apply-on-4-0-x

#2774 fix: add debug logs into HttpDeviceNotifier
  gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProvider.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
Labels: apply-on-master, apply-on-4-0-x

#2766 feat(perf): limit the number of request when a user is updated throug…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserService.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/scim/Address.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/scim/Attribute.java
  gravitee-am-policy/gravitee-am-policy-enrich-profile/src/main/java/io/gravitee/am/policy/enrich/profile/EnrichProfilePolicy.java
  gravitee-am-policy/gravitee-am-policy-enrich-profile/src/test/java/io/gravitee/am/policy/enrich/profile/EnrichProfilePolicyTest.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java
  gravitee-am-repository/gravitee-am-repository-api/src/test/java/io/gravitee/am/repository/management/api/UpdateActionsTest.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcOrganizationUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoOrganizationUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/CommonUserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/UserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/OrganizationUserServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
Labels: apply-on-master, apply-on-4-0-x

#2785 Plugins cta
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/LicenseResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/PlatformResource.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/GraviteeLicense.java
Labels: apply-on-master

#2791 fix: prevent null event or null evenType to be loaded
  gravitee-am-common/src/main/java/io/gravitee/am/common/event/UserEvent.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/event/EventManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/test/java/io/gravitee/am/gateway/event/EventManagerTest.java
  pom.xml
Labels: apply-on-master, apply-on-4-0-x

#2796 fix: verify domain settings when sending registration emails
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
Labels: apply-on-master

#2799 fix: prevent classloader issue for EnrollMFA policy
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/resources/plugin.properties
  pom.xml
Labels: apply-on-master

#2801 fix: fix default value initialization on HttpServerOptions
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxServerConfiguration.java
Labels: apply-on-master

#2802 fix: add UTM tag for the HTTP flow idp
  gravitee-am-ui/src/app/services/gio-license.service.ts
Labels: apply-on-master

#2806 fix: retrieve the correct email templates
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailManagerImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/EmailManagerTest.java
Labels: apply-on-master

#2798 feat(ui): use license resource to bind gravitee unlock popup
  gravitee-am-ui/src/app/app.module.ts
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.component.html
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.component.scss
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.component.ts
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.module.ts
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.stories.ts
  gravitee-am-ui/src/app/components/gio-license/gio-license.directive.ts
  gravitee-am-ui/src/app/components/gio-license/gio-license.module.ts
  gravitee-am-ui/src/app/components/gio-license/gio-license.service.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts
  gravitee-am-ui/src/app/domain/settings/factors/creation/steps/step1/step1.component.ts
  gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.ts
  gravitee-am-ui/src/app/domain/settings/resources/creation/steps/step1/step1.component.html
  gravitee-am-ui/src/app/domain/settings/resources/creation/steps/step1/step1.component.scss
  gravitee-am-ui/src/app/domain/settings/resources/creation/steps/step1/step1.component.ts
  gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.html
  gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.scss
  gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.ts
  gravitee-am-ui/src/app/entities/identity-providers/IdentityProvider.ts
  gravitee-am-ui/src/app/entities/plugins/Plugin.ts
  gravitee-am-ui/src/app/pipes/gio.pipe.module.ts
  gravitee-am-ui/src/app/services/organization.service.ts
Labels: apply-on-master

#2803 fix: remove useless configuration for SMTP as it is not an EE plugin
  gravitee-am-ui/src/app/components/gio-license/gio-license.service.ts
Labels: apply-on-master

#2812 fix: use good plugin name for SAML2.0
  gravitee-am-ui/src/app/components/gio-license/gio-license.service.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts
  gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.ts
Labels: apply-on-master

#2826 fix: avoid NullPointer during ManagementAPI sync process
  gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java
  gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/test/java/io/gravitee/am/management/services/sync/SyncManagerTest.java
Labels: apply-on-master, apply-on-4-0-x
