Repository gravitee-io/gravitee-access-management, pull requests merged in 2023-10, with the labels that each got.

#2943 fix(CI): pr env
  .circleci/config.yml
  .circleci/workflows.yml
  .github/workflows/publish-images-for-test-env.yml
  .github/workflows/remove-ready-to-test-labels.yml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3032 feat: create mjs scripts to trigger release steps
  .gitignore
  release/README.adoc
  release/helpers/circleci-helper.mjs
  release/helpers/logger.mjs
  release/package-lock.json
  release/package.json
  release/steps/1-step-release-git.mjs
  release/steps/2-step-release-maven-central.mjs
  release/steps/3-step-release-docker.mjs
  release/steps/4-step-release-rpm.mjs
  release/steps/5-step-release-helm.mjs
  release/steps/6-step-release-notes.mjs
  release/steps/abstract-step-release.mjs
  release/steps/am-release.mjs
  release/steps/generate_release_notes.mjs
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3011 feat(helm): Allow users to define extra manifests
  helm/Chart.yaml
  helm/templates/extra-manifests.yaml
  helm/tests/extra-manifests_test.yaml
  helm/values.yaml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-4-0-x

#3073 chore: include thymeleaf dep in depManagement to override the version used by vertx
  pom.xml
Labels: dependencies, apply-on-3-21-x, apply-on-3-20-x, ready_to_test

#3080 fix: align the Swagger annotation with the right Entity objet to list…
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserFactorsResource.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#2941 fix(idp-manager): do not stop the management API if an IdP plugin is missing or unknown
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3101 chore: upgrade gravitee BOM to 6.0.14
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/GraviteeVertxHttpServerRequest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpRequest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpResponse.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/dummies/DummyHttpRequest.java
  gravitee-am-ui/package-lock.json
  pom.xml
Labels: apply-on-master

#3122 fix: update enrolled factors in the user profile present into the exe…
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicy.java
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/test/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicyTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3128 fix: rework the previous fix for AM-757 as it doesn't work for some f…
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicy.java
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/test/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicyTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3120 chore: update latest version of mongo for running integration tests
  .circleci/workflows.yml
Labels: apply-on-4-1-x, apply-on-master

#3115 chore: upgrade jetty from 9.4.44 to 9.4.53
  pom.xml
Labels: apply-on-3-21-x

#3133 fix: avoid error when unknown text key is used into a template
  gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/FreemarkerMessageResolver.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/GraviteeMessageResolver.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/MessageFormatSanitizer.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/GraviteeMessageResolverTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/MessageFormatSanitizerTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3121 fix: evaluate password on server side for ResetPassword and ConfirmRe…
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/PasswordValidationHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/password-validation-v3.js
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/PasswordValidationHandlerTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/assets/preview/js/password-validation-v3.js
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html
  gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/password/PasswordSettingsStatus.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordServiceImplTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3137 fix: addition of LIST acl on DOMAIN permission for the ORGANIZATION_U…
  gravitee-am-ui/src/app/components/navbar/navbar.component.ts
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3150 fix: make confirmRegistration work when password history is enabled
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/password-validation-v3.js
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/assets/preview/js/password-validation-v3.js
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3151 fix: catch exceptionn during Resource creation
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/resource/impl/ResourceManagerImpl.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3152 fix: limit the concurrency for some Management API call to avoid floo…
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/EnvironmentsResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DomainsResource.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/PermissionService.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/utils/RepositoryConstants.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-4-1-x, apply-on-master

#3158 fix: always enable user created using SCIM if UserProvider is missing
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
Labels: apply-on-master

#3170 feat: manage to update the factor with fresh user information during …
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicy.java
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/java/io/gravitee/am/policy/enroll/mfa/configuration/EnrollMfaPolicyConfiguration.java
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/resources/schemas/schema-form.json
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/test/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicyTest.java
Labels: apply-on-master

#3173 chore: bump ldap idp version
  pom.xml
Labels: apply-on-master, apply-on-4-0-x

#3168 AM-1013 email verification disable confirm
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
Labels: apply-on-4-1-x, apply-on-master

#3180 fix: use the additional information coming from the lastest Identity …
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java
  gravitee-am-model/src/test/java/io/gravitee/am/model/UserTest.java
  pom.xml
Labels: apply-on-master
