Repository gravitee-io/gravitee-access-management, pull requests merged in 2023-11, with the labels that each got.

#3183 fix(helm): remove nonexistant existingClaim attribute
  helm/values.yaml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-4-0-x

#3182 feat(helm): backport HTTP 2 configuration from gravitee.yml to helm values
  helm/Chart.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_http_test.yaml
  helm/values.yaml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-4-0-x

#3196 fix: initialize SharedSecret and MovinFactor when required by SMS/CAL…
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicy.java
  gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/test/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicyTest.java
Labels: apply-on-3-21-x, apply-on-master, apply-on-4-0-x

#3198 fix: upgrade groovy policy to allow request headers usage
  pom.xml
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3171 fix: validate policy form before save
  gravitee-am-ui/package-lock.json
  gravitee-am-ui/package.json
  gravitee-am-ui/src/app/domain/applications/application/design/flows/flows.component.html
  gravitee-am-ui/src/app/domain/applications/application/design/flows/flows.component.ts
Labels: apply-on-master, ready_to_test

#3199 chore: bump france-connect idp version
  pom.xml
Labels: apply-on-master

#3208 fix: add consent settings into the values.yaml file
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/README.adoc
  helm/README.md
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway-configmap_test.yaml
  helm/values.yaml
Labels: apply-on-master

#3225 chore: bump france-connect idp
  pom.xml
Labels: apply-on-master

#3217 AM-867: conditionally print log based on exception type
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSessionHandler.java
Labels: apply-on-3-20-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3234 chore: bump france connect version
  pom.xml
Labels: apply-on-master

#3237 fix: improve default password policy to follow latest OWASP recommend…
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-model/src/main/java/io/gravitee/am/model/PasswordSettings.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/password/impl/DefaultPasswordValidatorImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/DefaultPasswordValidatorTest.java
  gravitee-am-test/specs/gateway/am-confirm-pre-registration.spec.ts
  gravitee-am-test/specs/gateway/am-selfaccount-change-password.jest.spec.ts
  gravitee-am-test/specs/gateway/enduser-logout.jest.spec.ts
  gravitee-am-test/specs/gateway/flow-execution.jest.spec.ts
  gravitee-am-test/specs/gateway/login-flow.jest.spec.ts
  gravitee-am-test/specs/gateway/remember-me.jest.spec.ts
  gravitee-am-test/specs/gateway/user-registration.jest.spec.ts
  postman/collections/graviteeio-am-openid-ciba-collection.json
Labels: apply-on-4-1-x, apply-on-4-0-x
