Repository gravitee-io/gravitee-access-management, pull requests merged in 2023-08, with the labels that each got.

#2829 fix(helm): surround special char with quote
  helm/Chart.yaml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#2823 fix: update migration script and Reporter class to manage the right i…
  gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/constants/MongoAuditReporterConstants.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
Labels: apply-on-master

#2833 [Snyk] Security upgrade org.thymeleaf:thymeleaf from 3.0.13.RELEASE to 3.1.2.RELEASE
  pom.xml
Labels: apply-on-master, apply-on-4-0-x

#2832 refactor: use license components from ui-particules
  gravitee-am-ui/angular.json
  gravitee-am-ui/package-lock.json
  gravitee-am-ui/package.json
  gravitee-am-ui/src/app/app.module.ts
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.component.html
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.component.scss
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.component.ts
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.module.ts
  gravitee-am-ui/src/app/components/gio-license/gio-ee-unlock-dialog/gio-ee-unlock-dialog.stories.ts
  gravitee-am-ui/src/app/components/gio-license/gio-license-data.spec.ts
  gravitee-am-ui/src/app/components/gio-license/gio-license-data.ts
  gravitee-am-ui/src/app/components/gio-license/gio-license.directive.ts
  gravitee-am-ui/src/app/components/gio-license/gio-license.module.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts
  gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.html
  gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.ts
  gravitee-am-ui/src/app/entities/plugins/Plugin.ts
  gravitee-am-ui/src/app/pipes/safe.pipe.ts
  gravitee-am-ui/src/assets/gio-license/am-idp-azure-ad.svg
  gravitee-am-ui/src/assets/gio-license/am-idp-cas.svg
  gravitee-am-ui/src/assets/gio-license/am-idp-france-connect.svg
  gravitee-am-ui/src/assets/gio-license/am-idp-kerberos.svg
  gravitee-am-ui/src/assets/gio-license/am-idp-ldap.svg
  gravitee-am-ui/src/assets/gio-license/am-idp-salesforce.svg
  gravitee-am-ui/src/assets/gio-license/am-idp-saml.svg
  gravitee-am-ui/src/assets/gio-license/am-idp-saml2.svg
  gravitee-am-ui/src/assets/gio-license/am-mfa-call.svg
  gravitee-am-ui/src/assets/gio-license/am-mfa-fido2.svg
  gravitee-am-ui/src/assets/gio-license/am-mfa-http.svg
  gravitee-am-ui/src/assets/gio-license/am-mfa-recovery-code.svg
  gravitee-am-ui/src/assets/gio-license/am-mfa-sms.svg
  gravitee-am-ui/src/assets/gio-license/am-smtp..svg
  gravitee-am-ui/src/assets/gio-license/gravitee-ee-upgrade.svg
  gravitee-am-ui/src/assets/gio-license/gravitee-risk-assessment.svg
  gravitee-am-ui/src/main.ts
  gravitee-am-ui/src/setupJest.ts
  gravitee-am-ui/src/styles.scss
Labels: apply-on-4-0-x

#2843 Update Changelog Generation
  .gitignore
  release/ci-steps/doc-new-release-notes.mjs
  release/helpers/changelog-helper.mjs
  release/helpers/jira-helper.mjs
Labels: apply-on-master

#2860 feat: align Alert Engine CTA with other OS
  gravitee-am-ui/src/app/app-routing.module.ts
  gravitee-am-ui/src/app/app.module.ts
  gravitee-am-ui/src/app/components/gio-license/gio-license-data.ts
  gravitee-am-ui/src/app/components/sidenav/sidenav.component.html
  gravitee-am-ui/src/app/components/sidenav/sidenav.component.ts
  gravitee-am-ui/src/app/guards/license-guard.service.ts
  gravitee-am-ui/src/app/services/navigation.service.ts
  gravitee-am-ui/src/assets/gio-license/alert-engine.png
  gravitee-am-ui/src/assets/gio-license/am-smtp.svg
Labels: apply-on-4-0-x

#2861 fix: resolve utm/license integration
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/LicenseResource.java
  gravitee-am-ui/package-lock.json
  gravitee-am-ui/package.json
  gravitee-am-ui/src/app/components/gio-license/gio-license-data.ts
  gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.html
  gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.ts
  gravitee-am-ui/src/app/entities/identity-providers/IdentityProvider.ts
Labels: apply-on-4-0-x

#2865 chore: bump guava to latest
  pom.xml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x

#2870 fix: unique constraints added for username
  gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/database/mariadb.schema
  gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/database/mysql.schema
  gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/database/sqlserver.schema
  gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_19_21/3.19.21-alter-users_username_unique.yml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-master, apply-on-4-0-x

#2878 fix: add missing statement to index creation script
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
Labels: apply-on-master
