Repository gravitee-io/gravitee-access-management, pull requests merged in 2023-09, with the labels that each got.

#2906 fix(docker): prevent $uri replacement in nginx configuration
  docker/management-ui/Dockerfile
  docker/management-ui/Dockerfile-dev
  docker/management-ui/Dockerfile-nightly
  docker/management-ui/config/default.conf
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-4-0-x

#2895 chore: include thymeleaf dep in depManagement to override the version…
  pom.xml
Labels: apply-on-master

#2884 fix: replace alert-engine png with svg image
  gravitee-am-ui/src/app/components/gio-license/gio-license-data.ts
  gravitee-am-ui/src/assets/gio-license/alert-engine.png
  gravitee-am-ui/src/assets/gio-license/alert-engine.svg
Labels: apply-on-master

#2920 fix: remember me default duration and hint text
  gravitee-am-ui/src/app/domain/components/account/account-settings.component.html
  gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts
Labels: apply-on-4-1-x

#2922 chore: reduce to sync delay to avoid flaky integration test
  .circleci/workflows.yml
Labels: apply-on-master

#2919 chore: upgrade gravitee-node to 4.2.0 to include account-linking in l…
  pom.xml
Labels: apply-on-master

#2896 AM-685: upgrade twilio resource in distribution
  pom.xml
Labels: apply-on-master

#2900 ci: deploy SNAPSHOT mvn artifact on build_branch job
  .circleci/workflows.yml
Labels: apply-on-master

#2939 fix(CI): in job-release_helm fix sed command to update Chart.yml
  .circleci/workflows.yml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#2951 fix: initialize missing idp properties based on the default schema value
  gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
Labels: apply-on-3-21-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#2952 fix: make index creation optional in mongo repository layer
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractMongoRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractManagementMongoRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/AbstractOAuth2MongoRepository.java
Labels: apply-on-3-21-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#2959 fix: add default error handler on path that are managing HTML rendering
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#2972 AM-838: replaced User and Client with respective property object
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
Labels: apply-on-4-1-x, apply-on-master

#2966 AM-766 SCIM group endpoint filter
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/groups/GroupsEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/GroupService.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/GroupServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/groups/GroupsEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/GroupServiceTest.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/GroupRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/AbstractDialectHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MsSqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MySqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/PostgresqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/ScimSearch.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcGroupRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcOrganizationUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelperTest.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoGroupRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/GroupRepositoryTest.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#2986 AM-777: fixed disabled create button issue
  gravitee-am-ui/src/app/components/json-schema-form/material-file.component.ts
Labels: apply-on-4-1-x, apply-on-master

#2987 fix(reg): set the registrationCompleted on user update
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#2965 feat(helm): Add podSecurityContext at deployment spec level
  helm/Chart.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/gateway/deployment_test.yaml
  helm/tests/ui/deployment_test.yaml
  helm/values.yaml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-4-0-x

#2981 feat(helm): allow ingress host wildcard
  helm/Chart.yaml
  helm/templates/api/api-ingress.yaml
  helm/templates/api/api-technical-ingress.yaml
  helm/templates/gateway/gateway-ingress.yaml
  helm/templates/gateway/gateway-technical-ingress.yaml
  helm/templates/ui/ui-ingress.yaml
  helm/tests/api/ingress_technical_test.yaml
  helm/tests/api/ingress_test.yaml
  helm/tests/gateway/ingress_technical_test.yaml
  helm/tests/gateway/ingress_test.yaml
  helm/tests/ui/ingress_test.yaml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-3-19-x, apply-on-4-1-x, apply-on-4-0-x

#3004 fix: Do not restrict the amil.allowedFrom to email.from value to avoi…
  .circleci/workflows.yml
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
Labels: apply-on-4-1-x, apply-on-master

#3017 fix: execute the delete notifier linked to the alert trigger
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcAlertTriggerRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/AlertTriggerRepositoryTest.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3018 AM-665: added searh fields
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/AbstractDialectHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelperTest.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParser.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3033 fix: avoid using emailFrom as default allowedFrom if the gravitee.yam…
  gravitee-am-service/src/main/java/io/gravitee/am/service/spring/email/EmailConfiguration.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/EmailDomainValidatorTest.java
Labels: apply-on-4-1-x, apply-on-master

#3046 chore: update changelog generation process
  .gitignore
  release/ci-steps/doc-new-release-notes.mjs
  release/helpers/changelog-helper.mjs
  release/helpers/jira-helper.mjs
Labels: apply-on-master
