Repository gravitee-io/gravitee-access-management, pull requests merged in 2023-12, with the labels that each got.

#3255 fix: Create a new instance of MessageDigest for each method call in P…
  gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/MessageDigestPasswordEncoder.java
Labels: apply-on-4-1-x, apply-on-master

#3243 fix: keep the SAML protocol info into the session on callbak failure
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/assertion/impl/ClientAssertionServiceImpl.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x

#3270 AM-699: Manage error when GeoIp service is not deployed
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/geoip/GeoIpHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/error/AsyncErrorCollector.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/geoip/GeoIpHandlerTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x

#3276 chore: addition of client secret hash settings into the helm chart
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/README.adoc
  helm/README.md
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/api-configmap_test.yaml
  helm/tests/gateway-configmap_test.yaml
  helm/values.yaml
Labels: apply-on-master

#3275 AM-688: Do not refer to company.com
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/WebAuthnFactoryTest.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/resources/schemas/schema-form.json
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/preview/PreviewBuilder.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/EntrypointResourceTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/EntrypointsResourceTest.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-policy/gravitee-am-policy-send-email/src/main/java/io/gravitee/am/policy/send/email/configuration/SendEmailPolicyConfiguration.java
  gravitee-am-policy/gravitee-am-policy-send-email/src/main/resources/schemas/schema-form.json
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EntrypointServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/EntrypointServiceTest.java
  gravitee-am-test/specs/gateway/flow-execution.jest.spec.ts
  gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html
  gravitee-am-ui/src/app/domain/components/emails/email/email.component.html
  helm/README.adoc
  helm/README.md
  helm/tests/api-configmap_test.yaml
  helm/values.yaml
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-4-1-x, apply-on-4-0-x

#3282 fix: exclude null value from scim UserMapper
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3301 fix: Evaluate the redirect_uri at each step of the auth flow
  gravitee-am-common/src/main/java/io/gravitee/am/common/exception/oauth2/RedirectMismatchException.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/RedirectUriValidationHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/par/impl/PushedAuthorizationRequestServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/par/PushedAuthorizationRequestServiceTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3307 AM-690: fix unable to list users
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/GroupMembersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/groups/GroupMembersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x

#3303 fix: preserve the clientSecret on application PATCH action when app w…
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
Labels: apply-on-master

#3302 fix: change the overview page for apps to highlight the fact clientSe…
  gravitee-am-ui/package-lock.json
  gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html
  gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
Labels: apply-on-master

#3322 chore(): add MFA Challenge policy & account-linking to the default bu…
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
  pom.xml
Labels: apply-on-master

#3318 feat(helm): add networkPolicy
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/common/networkpolicy.yaml
  helm/tests/common/networkPolicy_test.yaml
  helm/values.yaml
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3327 fix: generate a new CSRF token if the current one expired
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CSRFHandlerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSRFHandlerTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3326 fix: prevent to override factor enrollment
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3334 AM-1174: add correct error on duplicate externalId
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
Labels: apply-on-3-21-x, apply-on-3-20-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x

#3335 fix: provide the right parameters for an authorization_code flow
  gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html
Labels: apply-on-master

#3354 AM-13: sync every 1 sec
  .circleci/workflows.yml
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x

#3365 AM-1208 update ci config to reduce flaky integration tests and remove manual approval
  .circleci/workflows.yml
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x
