Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-07, with the labels that each got.

#4325 fix: missing transaction id in context
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-api/src/main/java/io/gravitee/am/gateway/handler/api/AbstractProtocolProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/transactionid/TransactionIdHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4334 fix: send registration confirmation form when user has no password
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4324 feat: aws secret manager certificate
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/plugins/CertificatesPluginResource.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts
  gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step1/step1.component.ts
  pom.xml
Labels: apply-on-4-5-x

#4365 fix: aws certificate cache
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
Labels: apply-on-4-5-x

#4368 fix: kafka reporter send record using audit referenceId key instead o…
  gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/audit/KafkaAuditReporter.java
Labels: apply-on-4-5-x

#4369 fix: close kafka producer connection without delay.
  gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/audit/KafkaAuditReporter.java
Labels: apply-on-4-5-x

#4377 fix: specify min cache value for certificate
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
Labels: apply-on-4-5-x

#4360 fix: validate OAuth2 settings on HTTP Resource
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/resource/ResourceValidatorImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/resource/http/HttpResourceValidator.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/resource/http/HttpResourceValidatorImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/resource/smtp/SmtpResourceValidatorImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/HttpResourceValidatorTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/ResourceValidatorTest.java
Labels: apply-on-4-5-x

#4380 fix: specify min cache value for certificate, update certificate aws plugin
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
Labels: apply-on-4-5-x

#4383 fix: incorrect state forms in application settings
  gravitee-am-ui/src/app/domain/applications/application/advanced/account/account.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/certificates/certificates.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/cookie/cookie.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/login/login.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/grantFlows/application-grant-flows.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/scopes/application-scopes.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/tokens/application-tokens.component.ts
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4327 AM-3359: fix: on 'tag' removal domain is updated only if it contains tag
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TagServiceImpl.java
Labels: apply-on-4-4-x, apply-on-4-5-x

#4382 fix: provide a settings to mitigate the breaking change introduce in 4.3
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2Request.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenEnhancerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2RequestTest.java
Labels: apply-on-4-4-x

#4393 fix: dynamic description for certificate plugin
  gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/resources/schemas/schema-form.json
  gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/resources/schemas/schema-form.json
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/main/java/io/gravitee/am/plugins/certificate/core/schema/CertificateSchema.java
  gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step2/step2.component.html
  gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step2/step2.component.ts
Labels: apply-on-4-5-x

#4394 AM-3270 MTLS for LDAP
  gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/DefaultTrustStoreProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/common/IdentityProviderConfigurationUtils.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/test/java/io/gravitee/am/identityprovider/api/common/IdentityProviderConfigurationUtilsTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientInitializer.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientOptionsConfigurer.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/IdentityProviderServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/utils/RetryWithDelay.java
  gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.ts
  gravitee-am-ui/src/app/domain/settings/providers/provider/provider.form.enricher.ts
  gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
Labels: apply-on-4-5-x

#4397 fix: add audit log with cause message
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/AuditBuilder.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4395 chore: introduce version attribute in the domain entity
  gravitee-am-model/src/main/java/io/gravitee/am/model/Domain.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/DomainVersion.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcDomain.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_0/4.5.0-domain-version.yml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/DomainMongo.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DomainRepositoryTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
Labels: apply-on-4-5-x

#4410 feat: AM-3270 MTLS for LDAP
  gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/DefaultTrustStoreProvider.java
  gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/UnsecuredKeyStore.java
  gravitee-am-certificate/gravitee-am-certificate-api/src/test/java/io/gravitee/am/certificate/api/DefaultTrustStoreProviderTest.java
  gravitee-am-certificate/gravitee-am-certificate-api/src/test/java/io/gravitee/am/certificate/api/UnsecuredKeyStoreTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientOptionsConfigurer.java
Labels: apply-on-4-5-x

#4414 fix: update mfa expression language links
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/selection-rule-dialog/selection-rule-dialog.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.html
Labels: apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4416 fix: scope in application settings
  gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/scopes/application-scopes.component.ts
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4421 fix: switching environments
  gravitee-am-ui/src/app/environment/environment.component.ts
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4399 feat: identify IdPs using a certificate
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/CertificateEntity.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/CertificateResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/CertificatesResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/CertificatesResourceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/CertificateServiceProxy.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateEntity.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateServiceProxyImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateStatus.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderServiceProxyImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/ModifiedCertificateEntity.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/CertificateEntityTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/CertificateServiceProxyImplTest.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/Certificate.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/IdentityProviderRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcIdentityProviderRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoIdentityProviderRepository.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/IdentityProviderService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/IdentityProviderServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/IdentityProviderServiceTest.java
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.html
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.scss
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts
Labels: apply-on-4-5-x

#4435 fix: environment hrid
  gravitee-am-ui/src/app/environment/environment.component.html
  gravitee-am-ui/src/app/environment/environment.component.ts
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4436 fix: get default certificate provider
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSession.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSessionHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieService.java
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4459 [4.3.x+] fix: copy all RememberDeviceSettings fields when updating an application
  gravitee-am-model/src/main/java/io/gravitee/am/model/RememberDeviceSettings.java
  gravitee-am-model/src/test/java/io/gravitee/am/model/RememberDeviceSettingsTest.java
Labels: apply-on-master, apply-on-4-4-x, apply-on-4-5-x

#4466 AM-3557 cert at applications pane issue
  gravitee-am-certificate/gravitee-am-certificate-api/src/test/java/io/gravitee/am/certificate/api/DefaultTrustStoreProviderTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/CertificatesResourceTest.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/Certificate.java
Labels: apply-on-master

#4461 fix: AM-3455 check credential count on WebAuthnLoginStep
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/AuthenticationFlowHandlerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/WebAuthnLoginStep.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieService.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/WebAuthnLoginStepTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieServiceTest.java
Labels: apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4468 feat: option to remove additional parameters from token response
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Labels: apply-on-4-5-x

#4476 AM-3560 usage column alignment
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.html
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.scss
Labels: apply-on-master

#4481 chore: remove helm release for alpha build
  .circleci/workflows.yml
Labels: apply-on-master

#4486 fix: delete domain with idp mtls
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4484 chore: upgrade reactor-netty
  pom.xml
Labels: apply-on-4-5-x

#4467 Relax OIDC provider config schema
  gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4482 fix: block override token standard response parameter.
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/Token.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenServiceTest.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4479 Add missing Gateway SSL settings to the helm chart
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_http_test.yaml
  helm/values.yaml
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4512 chore: new IDP LDAP plugin version
  pom.xml
Labels: apply-on-master

#4524 fix: remove mock factor when go back on enroll mfa
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4518 fix: break redirect loop when redirected to a hidden login form with …
  gravitee-am-common/src/main/java/io/gravitee/am/common/web/UriBuilder.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginHideFormHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginHideFormHandlerTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-4-x, apply-on-4-5-x

#4531 fix: block deleting the last default entrypoint on api level
  gravitee-am-service/src/main/java/io/gravitee/am/service/exception/LastDefaultEntrypointException.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EntrypointServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/EntrypointServiceTest.java
  gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.html
  gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.scss
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4546 fix: Extension grant with “create user account"
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationManager.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterV2.java
Labels: apply-on-4-5-x

#4545 AM-3602 consent delete issue
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-users/src/main/java/io/gravitee/am/gateway/handler/users/UsersProvider.java
  postman/collections/graviteeio-am-oauth2-collection-app-version.json
Labels: apply-on-master

#4550 fix: Extension grant with “create user account" - maintenance versions
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationManager.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x
