Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-12, with the labels that each got.

#5186 fix: adapt the AWS CloudHSM name in the Certificate list page
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts
Labels: apply-on-4-6-x

#5194 fix: remove tar file in the stages image to save space and remove the c…
  docker/gateway/Dockerfile-dev-noble
  docker/gateway/Dockerfile-noble
  docker/management-api/Dockerfile-dev-noble
  docker/management-api/Dockerfile-noble
Labels: apply-on-4-6-x

#5190 fix: provide a settings to mitigate the breaking change introduce in 4.3.
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2Request.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenEnhancerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2RequestTest.java
Labels: apply-on-master, apply-on-4-6-x

#5184 AM-4393 enroll validation
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/AbstractErrorHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
  gravitee-am-service/src/main/java/io/gravitee/am/service/exception/EnrollmentChannelValidationException.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/utils/vertx/RequestUtils.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5206 fix(ci): use the helm chart source to deploy on AKS to always used to…
  .circleci/workflows.yml
Labels: apply-on-master

#5189 fix: removed unused indexes
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractMongoRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractManagementMongoRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5205 fix: upgrade org.json to fix CVE-2023-5072
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5191 fix: use NotBlank instead of NotNull validation annotation in managem…
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewCertificate.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateCertificate.java
Labels: apply-on-master

#5199 chore: upgrade gravitee-node to 6.7.0 to include the CloudHSM feature…
  pom.xml
Labels: apply-on-master

#5182 feat: set latPasswordResetForNewUser
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/User.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/AbstractNewUser.java
Labels: apply-on-4-6-x

#5231 fix: If the user fills out the form a second time, they cannot be blo…
  gravitee-am-ui/src/app/domain/settings/certificates/certificate/certificate.component.ts
  gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step2/step2.component.ts
Labels: apply-on-master

#5233 AM-4492 audit log on psswd history
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
Labels: apply-on-master

#5235 chore: update ldap idp version
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x

#5230 fix: adapt the default password poklicy error message
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/password/impl/DefaultPasswordValidatorImpl.java
  postman/collections/graviteeio-am-self-account-management-collection-app-version.json
Labels: apply-on-master

#5239 AM-4512 missing cert schema
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateServiceProxyImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/CertificateServiceProxyImplTest.java
Labels: apply-on-master

#5246 fix: remove EventType.USER_PASSWORD_VALIDATION to generate an audit r…
  gravitee-am-common/src/main/java/io/gravitee/am/common/audit/EventType.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/services/AccountServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/PasswordPolicyRequestParseHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/user/PasswordPolicyRequestParseHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
Labels: apply-on-master

#5251 chore: addition of openapi spec
  docs/mapi/openapi.yaml
Labels: apply-on-4-6-x

#5250 fix: change field size for client
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_2_27/4.2.27-change-client-column-size.yml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DeviceRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/AccessTokenRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/AuthorizationCodeRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/CibaAuthRequestRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/PushedAuthorizationRequestRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/RefreshTokenRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/ScopeApprovalRepositoryTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5249 AM-4526: block creating users with future lastPasswordReset date
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
Labels: apply-on-master

#5244 fix: avoid change-after-check error in password policy component
  gravitee-am-ui/src/app/domain/settings/password-policy/pass-policy-status/password-policy-status.component.ts
  gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.html
  gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.ts
Labels: apply-on-4-6-x

#5262 chore(doc): update SCIM swagger specification to OpenAPI 3.0
  docs/scim-api-descriptor.yml
Labels: apply-on-4-6-x

#5277 fix: update certificate description in ui
  gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.html
Labels: apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5289 fix: idp configuration when certificate usage is missing
  gravitee-am-ui/src/app/domain/settings/providers/provider/provider.form.enricher.ts
Labels: apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5284 fix: bump ldap idp version
  pom.xml
Labels: apply-on-master
