Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-09, with the labels that each got.

#4715 fix: call the right method to update factor and avoid stackoverflow
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserService.java
Labels: apply-on-4-5-x

#4726 fix: avoid MFA Challenge if stepUp is not requiring it when the user …
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MfaFilterContext.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/AdaptiveMfaFilter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaChallengeCompleteFilter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaChallengeFilter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaSkipUserStronglyAuthFilter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/RememberDeviceFilter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/StepUpAuthenticationFilter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
Labels: apply-on-4-2-x

#4735 fix: provide role and permission in user profile
  gravitee-am-model/src/main/java/io/gravitee/am/model/safe/RoleProperties.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java
  gravitee-am-model/src/test/java/io/gravitee/am/model/safe/RolePropertiesTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4745 AM-3765 fix: added externalId nad sourceId to LOGOUT audit log
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
Labels: apply-on-master

#4750 chore: upgrade nginx base image to 1.26.2
  docker/management-ui/Dockerfile
  docker/management-ui/Dockerfile-dev
  docker/management-ui/Dockerfile-nightly
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4544 fix: keep app's redirect uri's query params on error
  gravitee-am-common/src/main/java/io/gravitee/am/common/web/ErrorInfo.java
  gravitee-am-common/src/main/java/io/gravitee/am/common/web/UriBuilder.java
  gravitee-am-common/src/test/java/io/gravitee/am/common/web/UriBuilderTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
  gravitee-am-test/package-lock.json
  gravitee-am-test/package.json
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-4-x, apply-on-4-5-x

#4777 fix: align label of 'domain whitelist' field
  gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.html
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-5-x

#4767 feat: create update username endpoint on self account
  docs/self-service-account-api-descriptor.yml
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/model/UpdateUsername.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountEndpointHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountResponseHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/util/AccountRoutes.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/AccountService.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountEndpointHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/services/AccountServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/business/UpdateUsernameRule.java
  gravitee-am-service/src/test/java/io/gravitee/am/business/UpdateUsernameRuleTest.java
  postman/collections/graviteeio-am-self-account-management-collection-app-version.json
Labels: apply-on-master

#4773 fix: restore the default contructor for WebClientBuilder as it is used by EE plugins
  gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4774 fix: provide enrolled factor in the MFA challenge template
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/factor/EnrolledFactor.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/safe/EnrolledFactorChannelProperties.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/safe/EnrolledFactorProperties.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java
Labels: apply-on-master, apply-on-4-4-x, apply-on-4-5-x

#4783 fix: add index on node_monitoring
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_0/4.5.0-add-node-monitoring-index.yml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoNodeMonitoringRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
Labels: apply-on-master

#4796 AM-3891 cert saml2
  gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.html
Labels: apply-on-master

#4791 fix: do not stop the bulk processor in reporter in case of error
  gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/audit/JdbcAuditReporter.java
  gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java
Labels: apply-on-master

#4801 AM-3890 jdbc cp down issue
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
Labels: apply-on-master

#4800 fix: accept upsert for domain user entity if the resilient mode is en…
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoOrganizationUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
Labels: apply-on-master

#4816 fix: make jdbc user repository to perform upserts on user update
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryInResilienceModeTest.java
Labels: apply-on-master

#4817 fix: addition of WARN to inform no event listener is available during…
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/event/EventManagerImpl.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4822 fix: provide null as default value for email.from placeholder
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailManagerImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailManagerImpl.java
Labels: apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4775 feat: fallback for missing 'repositories.gateway' prop group
  .circleci/workflows.yml
  gravitee-am-common/src/main/java/io/gravitee/am/common/env/RepositoriesEnvironment.java
  gravitee-am-common/src/test/java/io/gravitee/am/common/env/RepositoriesEnvironmentTest.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/PropertySourceFallbackConfigurer.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/PropertySourceFallbackConfigurer.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/audit/JdbcAuditReporter.java
  gravitee-am-reporter/gravitee-am-reporter-jdbc/src/test/java/io/gravitee/am/reporter/jdbc/audit/JdbcReporterJUnitConfiguration.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/Scope.java
  gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/ConnectionFactoryProvider.java
  gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/R2DBCConnectionProvider.java
  gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/utils/TlsOptionsHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/AbstractRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/gateway/GatewayRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/ManagementRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/OAuth2RepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/AbstractTestRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/provider/impl/MongoConnectionProvider.java
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/provider/impl/MongoFactory.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/gateway/AbstractGatewayMongoRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/gateway/GatewayRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/gateway/MongoScopeApprovalRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/ManagementRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/OAuth2RepositoryConfiguration.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/utils/BackendConfigurationUtils.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ReporterServiceTest.java
  gravitee-am-test/api/commands/utils/idps-commands.ts
  gravitee-am-test/api/config/dev.setup.js
  gravitee-am-test/specs/gateway/login-flow.jest.spec.ts
  gravitee-am-test/specs/gateway/password-policy-gateway.jest.spec.ts
  gravitee-am-test/specs/gateway/remember-me.jest.spec.ts
  gravitee-am-test/specs/gateway/user-registration.jest.spec.ts
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/api/configmap_repositories.yaml
  helm/tests/gateway/configmap_repositories.yaml
  pom.xml
Labels: apply-on-master

#4832 fix: introduce option to not force redirectUris during app creation
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4846 fix: issue with dbname resolution on test environments
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/gateway/GatewayRepositoryConfiguration.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/gateway/test/config/GatewayTestConfigurationLoader.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/management/test/config/ManagementTestConfigurationLoader.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/oauth2/test/config/OAuthTestConfigurationLoader.java
Labels: apply-on-master

#4845 chore(ci): integrate aquasec
  .circleci/workflows.yml
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#4820 AM-3685: support PKCE for identity providers
  gravitee-am-common/src/main/java/io/gravitee/am/common/crypto/CryptoUtils.java
  gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/Claims.java
  gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/CodeChallengeMethod.java
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-common/src/test/java/io/gravitee/am/common/crypto/CryptoUtilsTest.java
  gravitee-am-common/src/test/java/io/gravitee/am/common/oauth2/CodeChallengeMethodTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/JWTService.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/jwt/JWTServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackParseHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/code/AuthorizationCodeTokenGranter.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/common/Request.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectIdentityProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/social/SocialAuthenticationProvider.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractSocialAuthenticationProvider.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-google/src/main/java/io/gravitee/am/identityprovider/google/GoogleIdentityProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-google/src/test/java/io/gravitee/am/identityprovider/google/authentication/GoogleAuthenticationProviderTest.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json
Labels: apply-on-4-5-x

#4847 AM-3874 update idps in pom
  pom.xml
Labels: apply-on-master

#4813 chore: rewrite discovery oidc postman collection to jest test
  Makefile
  gravitee-am-test/api/fixtures/certificates.ts
  gravitee-am-test/specs/management/openid-discovery.jest.spec.ts
  postman/collections/graviteeio-am-openid-discovery-collection.json
Labels: apply-on-4-5-x

#4852 fix: load rememberDevice JS during resetPassword and registration
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/endpoints/user/RegisterConfirmationEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/endpoints/user/ResetPasswordEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterEndpointTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4856 fix: move user cache settings under user section instead of session s…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserStoreImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserStoreImplV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ConfigurationHelper.java
Labels: apply-on-master

#4853 fix: use phone_number claim as main value to preset the enrolledFacto…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4819 chore: remove deprecated methods in postman collection
  postman/collections/graviteeio-am-api-management-collection.json
  postman/collections/graviteeio-am-flows-collection-app-version.json
  postman/collections/graviteeio-am-login-collection-app-version.json
  postman/collections/graviteeio-am-logout-collection-app-version.json
  postman/collections/graviteeio-am-oauth2-collection-app-version.json
  postman/collections/graviteeio-am-oauth2-par-version.json
  postman/collections/graviteeio-am-openid-ciba-collection.json
  postman/collections/graviteeio-am-openid-core-collection-app-version.json
  postman/collections/graviteeio-am-openid-core-request-object-collection.json
  postman/collections/graviteeio-am-openid-dcr-collection-app-version.json
  postman/collections/graviteeio-am-openid-fapi-collection.json
  postman/collections/graviteeio-am-openid-jarm-collection.json
  postman/collections/graviteeio-am-uma2-app-version-collection.json
  postman/collections/graviteeio-am-user-management-collection-app-version.json
Labels: apply-on-4-5-x

#4860 fix: remove the maxLength for password expiry
  gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.html
  gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4879 fix: AM-3982: fix code verifier extraction
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackParseHandler.java
Labels: apply-on-4-5-x

#4843 AM-3962 PKCE support for IDP - management console
  gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/Claims.java
  gravitee-am-common/src/test/java/io/gravitee/am/common/oauth2/CodeChallengeMethodTest.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/social/SocialAuthenticationProvider.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/LoginController.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/SocialAuthenticationFilter.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-api/src/main/java/io/gravitee/am/plugins/handlers/api/core/impl/ConfigurationFactoryImpl.java
  gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.ts
Labels: apply-on-4-5-x

#4873 AM-3977 - fix: when old-way properties are provided then they should take precedence
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
Labels: apply-on-master

#4880 fix: on logout the client_id present as parameter takes precedence on…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4842 AM-3909 too verbose sync manager
  gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java
  pom.xml
Labels: apply-on-master

#4894 fix: create new indexes on scopeApproval to manage search on userId b…
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_0/4.5.0-scope-approval-external-user-id.yml
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/gateway/MongoScopeApprovalRepository.java
Labels: apply-on-master

#4891 fix: upgrade saml idp plugin from 3.0.4 to 3.0.5
  pom.xml
Labels: apply-on-master

#4890 fix: upgrade saml idp plugin from 3.0.4 to 3.0.5
  pom.xml
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4896 fix: handle missing code verifier gracefully, error handling improvement
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackParseHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProviderTest.java
Labels: apply-on-4-5-x

#4907 chore: upgrade ui-component and allows to commit yarn.lock
  gravitee-am-ui/.gitignore
  gravitee-am-ui/package.json
  gravitee-am-ui/yarn.lock
Labels: apply-on-master

#4909 chore: upgrade gravitee-bom from 8.0.4 to 8.1.16
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/GraviteeVertxHttpServerRequest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpRequest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/dummies/DummyHttpRequest.java
  pom.xml
Labels: apply-on-4-4-x

#4902 feat: checking gio_version param against version from pom.xml before release
  .circleci/workflows.yml
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x
