Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-04, with the labels that each got.

#3786 AM-2926 verbose error messages vol 2
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/ManagementApplication.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/provider/JacksonExceptionMapper.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/provider/JsonMappingExceptionMapper.java
Labels: apply-on-master

#3782 feat(saml2): add response binding option to service provider
  gravitee-am-common/src/main/java/io/gravitee/am/common/saml2/Binding.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSAMLSettings.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationSAMLSettingsMongo.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSAMLSettings.java
  gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.ts
Labels: apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3791 AM-2904: change info to debug log on geoip error
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/geoip/GeoIpHandler.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3813 chore(dep): upgrade gravitee bom to 7.0.19
  pom.xml
Labels: apply-on-4-3-x

#3814 chore(dep): upgrade gravitee bom to 6.0.40
  pom.xml
Labels: apply-on-4-2-x

#3824 fix: hide the domain name area in the navbar if no domain exist
  gravitee-am-ui/src/app/components/navbar/navbar.component.html
Labels: apply-on-master

#3825 fix: build JAX-RS response before calling resume for user notificatio…
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/UserNotificationsResource.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3827 fix: enroll optional when user has factor
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-3-x

#3840 fix: disable cors when origin is empty
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3822 chore(ci): fix changelog generation script to avoid editing manually …
  release/ci-steps/doc-new-release-notes.mjs
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#3867 chore: bump gravitee-am-idp-saml2 to 3.0.3
  pom.xml
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#3891 feat: allow users from external idp to have new attributes
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
  gravitee-am-ui/package-lock.json
  gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#3878 chore(ci): fix link generation for changelogs
  release/helpers/changelog-helper.mjs
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3896 fix: avoid exception when an event has a unknown type
  gravitee-am-common/src/main/java/io/gravitee/am/common/event/Type.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/mapper/EventConverter.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoEventRepository.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x

#3908 fix: typo on account registration configuration
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java
Labels: apply-on-master, apply-on-4-3-x

#3924 fix: update email if it was empty in the first place
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateUser.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/user/UserValidator.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/user/UserValidatorImpl.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#3930 AM- 2880 MFA should not be issued on silent auth
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MfaFilterContext.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaSkipUserSilentAuthFilter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaSkipUserSilentAuthFilterTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseIdTokenHintHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3862 fix: analytics timeout
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/AnalyticsParam.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AnalyticsServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java
  gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java
  gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/constants/MongoAuditReporterConstants.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ReporterServiceTest.java
  gravitee-am-ui/src/app/components/widget/widget.component.html
  gravitee-am-ui/src/app/components/widget/widget.component.scss
  gravitee-am-ui/src/app/domain/components/dashboard/dashboard.component.ts
  gravitee-am-ui/src/app/utils/time-range-utils.ts
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3949 AM-3306 fix: Limit on webauthn credentials sending back in a response
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStoreTest.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CredentialRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcCredentialRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringCredentialRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/CredentialRepositoryTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/CredentialService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CredentialServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/CredentialServiceTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3951 chore: release pipeline for a new version and an alpha version
  .circleci/config.yml
  .circleci/workflows.yml
  release/README.adoc
  release/steps/abstract-step-release.mjs
  release/steps/am-release-alpha-pipeline.mjs
  release/steps/am-release-pipeline.mjs
  release/steps/am-release.mjs
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3967 fix: make job not to use maven cache with corrupted lib
  .circleci/workflows.yml
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3959 AM-2887 fix: Added crucial MFA event logs
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3966 fix: NPE when applying MFA to app with legacy/broken MFA config
  gravitee-am-model/src/main/java/io/gravitee/am/model/Application.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/FactorSettings.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/MFASettings.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSettings.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplication.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationFactorSettings.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSettings.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchFactorSettings.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchMFASettings.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
Labels: apply-on-master
