Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-11, with the labels that each got.

#5089 AM-4257, AM-4301:remove user source and ext id from device query
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcDeviceRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DeviceRepositoryTest.java
Labels: apply-on-master, apply-on-4-6-x

#5084 AM-4056 missing audit target
  gravitee-am-common/src/main/java/io/gravitee/am/common/audit/Status.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AnalyticsServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/ApplicationAnalyticsServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/TagServiceImpl.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/I18nDictionary.java
  gravitee-am-reporter/gravitee-am-reporter-api/src/main/java/io/gravitee/am/reporter/api/audit/model/AuditOutcome.java
  gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/audit/AuditEntry.java
  gravitee-am-reporter/gravitee-am-reporter-file/src/test/java/io/gravitee/am/reporter/file/audit/FileAuditReporterTest.java
  gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/audit/JdbcAuditReporter.java
  gravitee-am-reporter/gravitee-am-reporter-jdbc/src/test/java/io/gravitee/am/reporter/jdbc/audit/JdbcAuditReporterTest.java
  gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/dto/AuditOutcomeDto.java
  gravitee-am-reporter/gravitee-am-reporter-kafka/src/test/java/io/gravitee/am/reporter/kafka/AuditValueFactory.java
  gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AuthenticationDeviceNotifierServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/BotDetectionServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EmailTemplateServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ExtensionGrantServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FactorServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FlowServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/GroupServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/I18nDictionaryService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/IdentityProviderServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/RoleServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ServiceResourceServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ThemeServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/DictionaryAuditBuilder.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/management/UserAuditBuilder.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/I18nDictionaryServiceTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ServiceResourceServiceTest.java
  gravitee-am-ui/src/app/domain/settings/audits/audits.component.html
  gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts
Labels: apply-on-master

#5086 chore(test): added max size bulk test
  gravitee-am-test/api/commands/management/service/utils.ts
  gravitee-am-test/specs/gateway/scim/bulk.spec.ts
  gravitee-am-test/specs/management/organisation.users.jest.spec.ts
  gravitee-am-test/specs/management/users.jest.spec.ts
Labels: apply-on-4-6-x

#5102 fix: align SCIM list behaviour with the RFC [BREAKING CHANGE]
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/groups/GroupsEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UsersEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/GroupServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/GroupServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/common/Page.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/GroupRepository.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/AbstractDialectHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MsSqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MySqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/PostgresqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcGroupRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/OffsetPageRequest.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoGroupRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/GroupRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
  gravitee-am-service/pom.xml
  pom.xml
Labels: apply-on-master

#5111 fix: replace flatMapSingle by concatMapSingle to preserve order
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-5-x

#5118 fix: ingore Unknown sub user during introspect
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/impl/IntrospectionServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/IntrospectionServiceTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5126 fix: create index on credentials using createdAt and username
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_1_0/4.1.35-update-web-credential-index.yml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5143 fix: manage missing GIS from token on DomainV2 introspect
  gravitee-am-common/src/main/java/io/gravitee/am/common/exception/jwt/InvalidGISException.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/impl/IntrospectionServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/IntrospectionServiceTest.java
Labels: apply-on-master, apply-on-4-6-x

#5128 chore(twilio): upgrade twilio version to 1.2.0
  pom.xml
Labels: apply-on-4-6-x

#5159 AM-4325 kafka reporter jsonform validation
  gravitee-am-ui/src/app/app-routing.module.ts
  gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.html
  gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5160 chore: upgrafe gravitee bom to 8.1.19
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5155 AM-4323 locking certificate upsert
  gravitee-am-ui/src/app/domain/settings/certificates/certificate/certificate.component.html
  gravitee-am-ui/src/app/domain/settings/certificates/certificate/certificate.component.ts
  gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.html
  gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.ts
Labels: apply-on-master

#5153 AM-4336 certs validation
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/JerseySpringTest.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-api/pom.xml
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-api/src/main/java/io/gravitee/am/plugins/handlers/api/core/PluginConfigurationValidator.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-api/src/main/java/io/gravitee/am/plugins/handlers/api/core/PluginConfigurationValidatorsRegistry.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-api/src/main/java/io/gravitee/am/plugins/handlers/api/plugin/AmPluginHandler.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-api/src/test/java/io/gravitee/am/plugins/handlers/api/core/PluginConfigurationValidatorTest.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-api/src/test/java/io/gravitee/am/plugins/handlers/api/core/PluginConfigurationValidatorsRegistryTest.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/main/java/io/gravitee/am/plugins/certificate/core/schema/CertificateSchema.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/main/java/io/gravitee/am/plugins/certificate/plugin/CertificatePluginHandler.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/main/java/io/gravitee/am/plugins/certificate/spring/CertificateSpringConfiguration.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/test/java/io/gravitee/am/plugins/certificate/core/schema/CertificateSchemaTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewCertificate.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PluginConfigurationPayload.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateCertificate.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/plugincfg/PluginJsonForm.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/plugincfg/PluginJsonFormValidator.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/plugincfg/PluginJsonFormValidatorTest.java
  gravitee-am-service/src/test/resources/certificate-aws-schema-definition.json
  gravitee-am-test/api/management/models/UpdateCertificate.ts
  gravitee-am-test/specs/management/certificates.jest.spec.ts
  gravitee-am-ui/src/app/services/certificate.service.ts
  pom.xml
Labels: apply-on-master
