Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-10, with the labels that each got.

#4918 chore(helm): add management of the sync service and cache layer
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/api/configmap_sync_test.yaml
  helm/tests/gateway/configmap_cache_test.yaml
  helm/tests/gateway/configmap_sync_test.yaml
Labels: apply-on-master

#4922 fix: add missing reference for some audit logs
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/ReporterServiceProxyImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ExtensionGrantServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/I18nDictionaryService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ThemeServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TokenServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/I18nDictionaryServiceTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/TokenServiceTest.java
Labels: apply-on-master

#4919 fix: AM-3945 username cannot be blank
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UserEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/users/UpdateUserEndpointHandlerTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/UsernameEntity.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UserResource.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/user/UserValidatorImpl.java
  gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
  gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4927 fix: avoid nullPointer when the login page is rendered due to invalid…
  gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java
Labels: apply-on-master

#4942 fix: AM-4058 SCIM no source
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
Labels: apply-on-master, apply-on-4-5-x

#4920 fix: AM-3945 blank username self management API
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/services/AccountServiceTest.java
Labels: apply-on-master

#4959 fix: PEN-11 json cfg validator
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/ReportersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ReportersResource.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewAlertNotifier.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewAuthenticationDeviceNotifier.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewBotDetection.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewCertificate.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewDeviceIdentifier.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewExtensionGrant.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewFactor.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewIdentityProvider.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewReporter.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewServiceResource.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateAuthenticationDeviceNotifier.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateBotDetection.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateCertificate.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateDeviceIdentifier.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateExtensionGrant.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateFactor.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateIdentityProvider.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateReporter.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateServiceResource.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/jsonstring/JsonString.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/jsonstring/JsonStringValidator.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/jsonstring/JsonStringValidatorTest.java
Labels: apply-on-master

#4964 fix: AM-4068 with 'includeLinkedIdentities'=true the mongo db query uses more…
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4965 chore(test): jest test for OIDC provider with PKCE
  gravitee-am-test/api/commands/management/domain-management-commands.ts
  gravitee-am-test/api/commands/utils/application-commands.ts
  gravitee-am-test/api/commands/utils/misc.ts
  gravitee-am-test/api/commands/utils/retry.ts
  gravitee-am-test/api/config/dev.setup.js
  gravitee-am-test/specs/gateway/idp-with-pkce.spec.ts
Labels: apply-on-4-5-x

#4941 feat(helm): allow configuring security section of management api conf…
  helm/templates/api/api-configmap.yaml
  helm/tests/api/configmap_security_test.yaml
  helm/values.yaml
Labels: apply-on-4-5-x

#4966 fix: added hash of error to the session
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-common/src/main/java/io/gravitee/am/common/web/UriBuilder.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/HashUtil.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/endpoint/ErrorEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/AbstractErrorHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/register/RegisterFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/consent/UserConsentFailureHandler.java
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4980 fix: added hash of error to the session for invalid token
  gravitee-am-common/src/main/java/io/gravitee/am/common/exception/oauth2/InvalidTokenException.java
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserTokenRequestParseHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/ResetPasswordOneTimeTokenHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/register/RegisterVerifyRequestParseHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterVerifyEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/user/register/RegisterVerifyRequestParseHandlerTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4985 Fix AM-4080 no password policy at confirm reg page
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/endpoints/user/RegisterConfirmationEndpointTest.java
Labels: apply-on-master, apply-on-4-5-x

#4996 fix: helm charts should be used in branch version
  .circleci/workflows.yml
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-5-x

#5007 fix: http status code on rate limit exception
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/exception/MFAValidationAttemptException.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/exception/RateLimitException.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4954 feat(helm): rework gateway probes definition with default value and customisation
  helm/templates/api/_api-deployment-probes.tpl
  helm/templates/api/api-deployment.yaml
  helm/templates/gateway/_gateway-deployment-probes.tpl
  helm/templates/gateway/gateway-deployment.yaml
  helm/tests/api/configmap_sync_test.yaml
  helm/tests/api/deployment_probes_test.yaml
  helm/tests/gateway/configmap_sync_test.yaml
  helm/tests/gateway/deployment_probes_test.yaml
  helm/values.yaml
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5024 fix: find user by externalId in extension grant.
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterV2.java
Labels: apply-on-4-5-x

#5037 fix: display server error when session is empty.
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5042 fix: op claims in additional information
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/FreemarkerDataHelper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/uma/UMATokenGranter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/notifications/NotificationDefinitionUtils.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java
  gravitee-am-model/src/test/java/io/gravitee/am/model/safe/UserPropertiesTest.java
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5053 fix: remove saml idp from organization level
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/plugins/IdentityProvidersPluginResource.java
  gravitee-am-ui/src/app/app-routing.module.ts
  gravitee-am-ui/src/app/app.module.ts
  gravitee-am-ui/src/app/resolvers/identities-organization.resolver.ts
  gravitee-am-ui/src/app/services/organization.service.ts
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5059 chore: update ipfiltering version
  pom.xml
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5076 Disable creating service users in domains
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/AbstractNewUser.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewOrganizationUser.java
Labels: apply-on-master, apply-on-4-5-x

#5074 fix: unable to add additional information on user create
  gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.ts
  gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
Labels: apply-on-4-4-x, apply-on-4-5-x
