Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-08, with the labels that each got.

#4559 AM-3597: properly toggle "entrypoint unavailable" warning
  gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.html
  gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.scss
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-5-x

#4558 AM-3655 fix jwt-bearer for SubjectManagerV2
  gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/main/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JWTBearerExtensionGrantProvider.java
  gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/test/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JWTBearerExtensionGrantProviderTest.java
Labels: apply-on-master

#4571 fix: audits present twice during user creation
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgraderTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4573 fix: provide UUID generated based on the internal sub for Domain in v2
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2Test.java
Labels: apply-on-4-5-x

#4582 fix: remove null from gis
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/SubjectManager.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV1.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/spring/SecurityDomainRouterConfiguration.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2Test.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterV2.java
Labels: apply-on-4-5-x

#4583 Fix/am 3386
  gravitee-am-ui/src/app/domain/settings/providers/provider/roles/roles.component.html
Labels: apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4580 AM-3650 Double dashes
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeGenerator.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeGeneratorTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4595 fix: Extension grant with “create user account"
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2Test.java
Labels: apply-on-4-5-x

#4594 fix: sanitize secret from EnrolledFactor
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/util/AccountRoutes.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4605 chore: update cockpit version
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4611 chore: added more debug logs on failed MFA validation
  gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/api/OTPFactorProvider.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4612 fix: add missing env variables
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/api-configmap_test.yaml
  helm/tests/gateway-configmap_test.yaml
  helm/values.yaml
Labels: apply-on-4-5-x

#4572 AM-3499 OIDC idp secret input should be password
  gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.ts
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-5-x

#4619 fix: helm chart and properties values
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
Labels: apply-on-4-5-x

#4626 fix: debug log in OTP factory
  gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/api/OTPFactorProvider.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4632 Fix/am 3700
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/api/AccessTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/api/RefreshTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAccessTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcRefreshTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAccessTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoRefreshTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/AccessTokenRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/RefreshTokenRepositoryTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/TokenService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TokenServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4597 feat: AM-3525: support device lookup by users' externalId + source
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RiskAssessmentService.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/utils/RiskAssessmentServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/rememberdevice/DeviceIdentifierHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/rememberdevice/DeviceIdentifierHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/risk/RiskAssessmentHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/risk/RiskAssessmentHandlerTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DeviceResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DevicesResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/DevicesResourceTest.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/Device.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/UserId.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/DeviceRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/AbstractJdbcRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcDeviceRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcDevice.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_0/4.5.0-device-external-user-id.yml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDeviceRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/DeviceMongo.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DeviceRepositoryTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/DeviceService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DeviceServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/DeviceServiceTest.java
Labels: apply-on-4-5-x

#4645 fix: bot detection creation nullpointer
  gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/provider/spring/HttpAuthenticationDeviceProviderSpringConfiguration.java
  gravitee-am-botdetection/gravitee-am-botdetection-recaptcha-v3/src/main/java/io/gravitee/am/botdetection/google/recaptcha/provider/GoogleReCaptchaV3Provider.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-facebook/src/main/java/io/gravitee/am/identityprovider/facebook/authentication/spring/FacebookAuthenticationProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/spring/GithubAuthenticationProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/test/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProviderTestConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-google/src/main/java/io/gravitee/am/identityprovider/google/authentication/spring/GoogleAuthenticationProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/authentication/spring/HttpAuthenticationProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/spring/HttpUserProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/authentication/HttpAuthenticationProviderTestConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-linkedin/src/main/java/io/gravitee/am/identityprovider/linkedin/authentication/spring/LinkedinAuthenticationProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/test/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProviderTestConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-twitter/src/main/java/io/gravitee/am/identityprovider/twitter/authentication/spring/TwitterAuthenticationProviderConfiguration.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/spring/WebClientsConfiguration.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/http/WebClientBuilderTest.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4653 fix: added secret and watch to helm charts
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_http_test.yaml
  helm/values.yaml
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4654 fix: one installation collection
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/InstallationServiceImpl.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4664 fix: previous gravitee.yml should be compatible with 4.5 version wher…
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/GatewayTypeBeanFactoryFallbackPostProcessor.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/GatewayTypeBeanFactoryFallbackPostProcessor.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java
Labels: apply-on-master

#4666 fix: redirect_url not required for registration confirmation
  gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/TokenPurpose.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidatorTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4667 fix: mfa remember device space
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.html
Labels: apply-on-4-1-x

#4676 fix: add space on newsletter page
  gravitee-am-ui/src/app/newsletter/newsletter.component.scss
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4677 fix: remove tokens by correct client id
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TokenServiceImpl.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4688 fix: added GraviteeTPMAttestation to fix reading PubArea section
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/attestation/GraviteeTPMAttestation.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/attestation/PubArea.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/META-INF/services/io.vertx.ext.auth.webauthn.impl.attestation.Attestation
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#4675 fix: colon is forbidden character and cannot be used in changelog
  helm/Chart.yaml
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4702 fix: upgrade ldap idp version to fix connection issues
  pom.xml
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4703 fix: upgrade ldap idp version to fix connection issues
  pom.xml
Labels: apply-on-4-5-x

#4714 fix: create application with empty string to default behaviour
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x
