Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-01, with the labels that each got.

#3379 AM-1085: bug fixed by implementing same behaviour in different scenarios
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
  gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3380 fix: add javax-annotation dependency to initialize Handler in AE Comm…
  gravitee-am-service/pom.xml
  pom.xml
Labels: apply-on-master, apply-on-4-2-x

#3383 fix: bypass BodyHandler on GET method
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/ConditionalBodyHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/ConditionalBodyHandlerTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3399 fix: provide the WebAuthn credentialId value in the ExpressionLanguag…
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RoutingContextHelper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/utils/RoutingContextHelperTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
Labels: apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3408 chore(perf): provide gatling Docker image
  gravitee-am-performance/Dockerfile
  gravitee-am-performance/README.md
  gravitee-am-performance/scripts/entrypoint.sh
Labels: apply-on-master

#3414 feat(flows): add WebAuthn credential register flow
  gravitee-am-common/src/main/java/io/gravitee/am/common/policy/ExtensionPoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/impl/FlowManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/FlowEntity.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/flow/Type.java
  gravitee-am-service/src/main/resources/flow/am-schema.json
  gravitee-am-service/src/test/java/io/gravitee/am/service/FlowServiceTest.java
Labels: apply-on-master, apply-on-4-2-x

#3417 chore: upgrade JSON-PATH from 2.8.0 to 2.9.0
  pom.xml
Labels: apply-on-master, apply-on-4-2-x

#3427 fix: apply timeout on blockingGet made in the REST API
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/JWTAuthenticationFilter.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/security/ManagementAuthenticationProvider.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java
Labels: apply-on-master, apply-on-4-2-x
