Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-05, with the labels that each got.

#3975 fix: added keystore.password in gateway-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3990 chore: update node version
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3996 AM-2887 MFA logs 2
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#4016 Fixed not encode certificate header
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/provider/CertificateUtils.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-3-x, apply-on-4-4-x

#4026 fix: AM-3180 - SHA iteration rounds for Default IDPs
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/IdentityProviderManagerTest.java
Labels: apply-on-master

#4028 fix: align PasswordPolicyService.retrievePasswordPolicy method behavi…
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java
Labels: apply-on-master

#4033 chore: upgrade gravitee bom to 8.x and gravtee-node to 5.14.3
  pom.xml
Labels: apply-on-master

#4031 fix: rework the forceResetPassword feature to improve UX and define t…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/AuthenticationFlowHandlerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/ForceResetPasswordStep.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/ForceResetPasswordStepTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordSubmissionEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserRequestHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordSubmissionEndpointTest.java
Labels: apply-on-master

#4030 fix: "skip remember device" not being saved when using JDBC storage
  gravitee-am-model/src/main/java/io/gravitee/am/model/RememberDeviceSettings.java
  gravitee-am-model/src/test/java/io/gravitee/am/model/RememberDeviceSettingsTest.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/RememberDeviceSettingsMongo.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/ApplicationRepositoryTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchRememberDeviceSettings.java
Labels: apply-on-master, apply-on-4-4-x

#4035 AM-2999 Uploading Certificates for mTLS
  gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/ConfigurationCertUtils.java
  gravitee-am-certificate/gravitee-am-certificate-api/src/test/java/io/gravitee/am/certificate/api/ConfigurationCertUtilsTest.java
  gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/resources/schemas/schema-form.json
  gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/resources/schemas/schema-form.json
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/jwk/impl/JWKServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/jwk/JWKServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/CertificateEntity.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/CertificatesResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/CertificatesResourceTest.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcCertificateRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCertificateRepository.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
  gravitee-am-ui/src/app/components/dialog/confirm/confirm.component.html
  gravitee-am-ui/src/app/components/dialog/confirm/confirm.component.scss
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.html
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.scss
  gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts
Labels: apply-on-master

#4044 fix: unable to remove a form at organization level.
  gravitee-am-ui/src/app/domain/components/forms/form/form.component.ts
Labels: apply-on-4-4-x

#3937 fix: enforce sanitizeTemplate method
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationServiceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
Labels: apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#4055 chore: upgrade gravitee-bom to 6.0.47
  pom.xml
Labels: apply-on-4-2-x

#4054 fix: max consecutive letters in password policy
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchPasswordSettings.java
  gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.ts
  gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html
  gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4045 fix: don't require a redirect_uri param in the reset password flow
  gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/TokenPurpose.java
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/RedirectUriValidationHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidatorTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4064 fix: unable to remove form at organization level
  gravitee-am-ui/src/app/domain/components/forms/form/form.component.ts
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x

#4073 fix: service name in dialog
  gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
Labels: apply-on-4-4-x

#4074 fix: added service account documentation
  gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.html
Labels: apply-on-4-4-x

#4057 fix: save button wont be refreshed when changing time with the input arrow
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.html
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4088 chore: refactor to use the new asSafeClient method everytime a saniti…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutCallbackEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/management/ApplicationAuditBuilder.java
Labels: apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#4094 chore: update mfa challenge library
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4095 fix: make DomainProperties object available into EL context
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/ReactableExecutionContext.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/provider/DomainTemplateVariableProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/resources/META-INF/spring.factories
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4124 fix: define passwordEncoder as required for HTTP Provider to force a …
  gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/resources/schemas/schema-form.json
Labels: apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4105 fix: proper handling CertificateWithApplicationException
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
Labels: apply-on-4-1-x, apply-on-4-0-x

#4120 fix: manage linked identities for brute force detection
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserService.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_1_0/4.1.23-update-user-identities-table.yml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/UserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4136 fix: introduce legacy settings to filter out the custom prompt values
  gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/Prompt.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/impl/OpenIDDiscoveryServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/discovery/OpenIDDiscoveryServiceTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4149 fix: copy application settings and flow during DCR request using temp…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/ClientServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationServiceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/FlowService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FlowServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/FlowServiceTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4164 chore: update JMV HEAP up to 512m and remove connection errors during…
  .circleci/workflows.yml
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4178 fix: addition of username into user identities to be able to manage b…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/UserIdentity.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcUser.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_1_0/4.1.23-update-user-identities-table.yml
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x
