Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-03, with the labels that each got.

#3609 fix: evaluate legacy ForceEnrollment value using Boolean.False to avo…
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ApplicationFactorSettingsUpgrader.java
Labels: apply-on-master

#3625 AM-2700: am-factor-call and am-factor-sms upgrade
  pom.xml
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x

#3624 fix: redirect to default error page if the client only have client_cr…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3636 AM-2700- upgraded intl-tel-input JS plugin
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/intl-tel-input-19.5.7-utils.js
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/intl-tel-input-19.5.7.min.js
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3635 AM-2161: on login=prompt authorized used should be removed from the s…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3637 fix: revert fix for gravitee-io/issues#9494
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3656 chore: upgrade gravitee-bom
  pom.xml
Labels: apply-on-4-2-x

#3657 chore: upgrade gravitee bom to 7.0.14
  pom.xml
Labels: apply-on-master

#3676 AM-2846: fix recovery icon display
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/factors-select-dialog/factors-select-dialog.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select-icon.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.html
Labels: apply-on-master

#3648 fix: upgrade recovery code policy to avoid useless audit logs
  pom.xml
Labels: apply-on-master

#3661 AM-2847 default factor glitch
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchFactorSettings.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/model/PatchFactorSettingsTest.java
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.ts
  postman/collections/graviteeio-am-self-account-management-collection-app-version.json
Labels: apply-on-master

#3668 AM-2873: update particles
  gravitee-am-ui/package-lock.json
  gravitee-am-ui/package.json
Labels: apply-on-4-3-x

#3643 fix: save factor metadata on challenge step if the provider is using …
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java
Labels: apply-on-master

#3674 AM-2717 MFA enrolment views fixes
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.scss
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.scss
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.scss
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.scss
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/selection-rule-dialog/selection-rule-dialog.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/selection-rule-dialog/selection-rule-dialog.component.scss
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.scss
Labels: apply-on-master

#3688 AM-2718 MFA challenge minor fixes
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.html
Labels: apply-on-master

#3658 fix: evaluate user identities in addition of the source in the SSOHan…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandlerTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#3693 fix: do not consider the MFA Challenge/Enrollment as completed into t…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java
Labels: apply-on-master

#3695 AM-2717: update title and placeholder in mfa conditional component
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.html
Labels: apply-on-master

#3694 AM-2756: fix user activities list
  gravitee-am-ui/src/app/components/snackbar/snackbar.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/expression-info-dialog/expression-info-dialog.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/tokens/dialog/claims-info.component.html
  gravitee-am-ui/src/app/domain/settings/groups/group/settings/settings.component.html
  gravitee-am-ui/src/app/domain/settings/providers/provider/roles/roles.component.html
  gravitee-am-ui/src/app/domain/settings/scopes/creation/scope-creation.component.html
  gravitee-am-ui/src/app/domain/settings/scopes/scope/scope.component.html
  gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
Labels: apply-on-master

#3700 AM-2814: ui mfa fixes banner info
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.scss
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/risk-based/mfa-risk-based.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.scss
  gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.scss
Labels: apply-on-master

#3696 fix: update UserIdentity list on RDBMS backends
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/UserIdentity.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#3706 AM-2756: resize item title user activites
  gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.scss
Labels: apply-on-master

#3710 AM-2868: add dynamic form error space
  gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.scss
Labels: apply-on-master

#3709 fix: allow to set a String array as aud custom value
  gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/JWT.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenServiceTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3720 AM-2868: dynamic form error fix
  gravitee-am-ui/src/app/domain/alerts/notifiers/notifier/form/form.component.scss
  gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/form/form.component.scss
  gravitee-am-ui/src/app/domain/settings/certificates/certificate/form/form.component.scss
  gravitee-am-ui/src/app/domain/settings/deviceidentifiers/device-identifier/form/form.component.scss
  gravitee-am-ui/src/app/domain/settings/extension-grants/extension-grant/form/form.component.scss
  gravitee-am-ui/src/app/domain/settings/factors/factor/form/form.component.scss
  gravitee-am-ui/src/app/domain/settings/openid/ciba/device-notifiers/device-notifier/form/form.component.scss
  gravitee-am-ui/src/app/domain/settings/resources/resource/form/form.component.scss
Labels: apply-on-master

#3722 fix: make webAuthnCredentialInternalId available into the session
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnResponseHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/consent/UserConsentPrepareContextHandler.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/CredentialService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CredentialServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/CredentialServiceTest.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-master, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3736 fix: undefined in userAgent
  gravitee-am-ui/src/app/domain/settings/audits/audit/audit.component.html
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3751 AM-2861: fix ldap user group field
  gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x

#3761 chore: restore the commented out Postman collection
  Makefile
  postman/collections/graviteeio-am-openid-core-request-object-collection.json
  postman/generate-encrypted-request-object.adoc
Labels: apply-on-master

#3767 AM-2163: purge ciba records for sql db
  gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-purge/src/main/java/io/gravitee/am/management/services/purge/ScheduledPurgeService.java
  gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-purge/src/main/java/io/gravitee/am/management/services/purge/TableName.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcLoginAttemptRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPermissionTicketRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAccessTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAuthorizationCodeRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcPushedAuthorizationRequestRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcScopeApprovalRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/oidc/JdbcCibaAuthReqRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/oidc/JdbcRequestObjectRepository.java
Labels: apply-on-3-21-x, apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x
