Repository gravitee-io/gravitee-access-management, pull requests merged in 2024-06, with the labels that each got.

#4187 fix: update organization user email after authentication
  gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4209 AM-3292 mtls openid delete cert
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectConfigurationUtils.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/test/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectConfigurationUtilsTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/IdentityProviderServiceImpl.java
Labels: apply-on-master

#4211 fix: prevent create and update policy with default flag.
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java
Labels: apply-on-4-4-x

#4216 chore: bump gravitee-node version
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#3623 fix: http redirection to https
  helm/CHANGELOG.md
  helm/values.yaml
Labels: apply-on-4-1-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4230 fix: Remove more general duplicated "user" block in Helm chart
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/api/configmap_user_test.yaml
  helm/tests/gateway/configmap_user_test.yaml
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4256 fix: avoid infinite blocking call durint Indexes creation
  gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractMongoRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractManagementMongoRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAccessPolicyRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAccountAccessTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAuthenticationDeviceNotifierRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAuthenticationFlowContextRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoBotDetectionRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCertificateRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDeviceIdentifierRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDeviceRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoEmailRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoEntrypointRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoEnvironmentRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoEventRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoExtensionGrantRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoFactorRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoFlowRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoFormRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoGroupRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoI18nDictionaryRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoIdentityProviderRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoLoginAttemptRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoMembershipRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoNodeMonitoringRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoNotificationAcknowledgeRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordHistoryRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordPolicyRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPermissionTicketRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoRateLimitRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoReporterRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoResourceRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoRoleRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoScopeRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoServiceResourceRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoTagRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoThemeRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserActivityRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserNotificationRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoVerifyAttemptRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/AbstractOAuth2MongoRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAccessTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAuthorizationCodeRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoCibaAuthRequestRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoPushedAuthorizationRequestRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoRefreshTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoRequestObjectRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoScopeApprovalRepository.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4272 fix: adapt nginx config to manage the new rw www directory
  docker/compose/config/nginx.conf
  docker/management-ui/Dockerfile
  docker/management-ui/Dockerfile-dev
  docker/management-ui/Dockerfile-nightly
  docker/management-ui/config/default.conf
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4280 AM-3317 fix: StackOverflowError on Kubernetes websocket connection issues
  pom.xml
Labels: apply-on-4-3-x, apply-on-4-4-x

#4281 chore: increase the resource class for deploy-snapshot-on-nexus to av…
  .circleci/workflows.yml
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4307 chore: update saml library
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#4306 AM-3318 fix: obsolete gv-expression-language quirks.
  gravitee-am-ui/src/app/app.module.ts
  gravitee-am-ui/src/app/directives/gv-expression-language-style-reapply.directive.ts
  gravitee-am-ui/src/app/domain/applications/application/idp/selection-rule/create/create.component.html
  gravitee-am-ui/src/app/domain/settings/providers/provider/mappers/create/create.component.html
  gravitee-am-ui/src/app/domain/settings/providers/provider/mappers/mappers.component.html
  gravitee-am-ui/src/app/domain/settings/providers/provider/roles/create/create.component.html
Labels: apply-on-master

#4314 fix: added validation of OTP
  gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/api/OTPFactorProvider.java
  gravitee-am-factor/gravitee-am-factor-api/src/test/java/io/gravitee/am/factor/api/OTPFactorProviderTest.java
Labels: apply-on-4-1-x, apply-on-4-0-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x
