Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-05, with the labels that each got.

#5806 chore: upgrade nginx to 1.27.5
  docker/management-ui/Dockerfile
  docker/management-ui/Dockerfile-dev
Labels: apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x

#5833 fix: use the Sprint implementation of BCrypt encoder
  gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/spring/MongoAuthenticationProviderConfiguration.java
  gravitee-am-service/pom.xml
  gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/bcrypt/BCrypt.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/bcrypt/BCryptPasswordEncoder.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/BCryptPasswordEncoderTest.java
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5826 chore: bump france-connect dependency to 3.1.0 to support FranceConne…
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#5824 fix: define default implementation for SocialIdentityProviderConfigur…
  gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/social/SocialIdentityProviderConfiguration.java
Labels: apply-on-master

#5819 fix: AM-5001 membership collects org users
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationMembersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/MembersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/members/MembersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/MembersResourceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/MembershipService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5866 fix: preserve the HRID on organization update
  gravitee-am-model/src/main/java/io/gravitee/am/model/Organization.java
  gravitee-am-model/src/test/java/io/gravitee/am/model/OrganizationTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5875 fix: remove invalid settings from the values.yaml example
  helm/values.yaml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5901 chore: upgrade aqua orb to 1.0.5
  .circleci/workflows.yml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5907 fix: filter Metadata from the Certificate audits
  gravitee-am-model/src/main/java/io/gravitee/am/model/Certificate.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/management/CertificateAuditBuilder.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/reporter/builder/CertificateAuditBuilderTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x
