Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-03, with the labels that each got.

#5580 AM-4842 fix: redirect_uri validation
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidatorTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5592 AM-4816 fingerprintjs store
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/fp/fp.min.js
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/remember-device/fingerprintjs-v3-gravitee.js
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login_callback_device_identifier.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_login.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/assets/preview/js/fp/fp.min.js
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/assets/preview/js/remember-device/fingerprintjs-v3-gravitee.js
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_login.html
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5571 fix: added dynamic user groups for jdbc
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcUser.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringDynamicUserGroupRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_11/4.5.11-dynamic-user-groups.yml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Labels: apply-on-4-6-x, apply-on-4-5-x

#5601 chore(dep): update account-linking policy to include the 2.0.0-alpha …
  pom.xml
Labels: apply-on-master

#5577 feat: add preRegistration for SCIM
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceImplTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/ProvisioningUserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/ProvisioningUserServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/registration_confirmation.html
  gravitee-am-test/specs/gateway/scim/scim.spec.ts
Labels: apply-on-4-7-x

#5605 fix: warn when domain not found on event sync
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EventServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/EventServiceTest.java
Labels: apply-on-4-7-x

#5609 fix: default expiry time and client in email (AM-4859)
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/ProvisioningUserServiceImpl.java
Labels: apply-on-4-7-x

#5610 fix(dataplane): remove reference to the domin in USerGatewayService signature
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserGatewayService.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserGatewayServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserGatewayServiceImplV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2Test.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequestResolver.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestParametersHandlerTest.java
Labels: apply-on-master

#5608 fix: update webauthn origin to dataplane gatewayurl if its missing
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/SecurityDomainRouterFactory.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterCredentialsEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterSuccessEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnResponseHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterSuccessEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandlerTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/DomainDataPlane.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/DomainDataPlaneTest.java
Labels: apply-on-master

#5619 AM-4848 fix: update webauth origin to dataplane gateway url
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/core/SingleDataPlaneLoader.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/test/java/io/gravitee/am/plugins/dataplane/core/SingleDataPlaneLoaderTest.java
Labels: apply-on-master

#5627 chore: update liquibase
  pom.xml
Labels: apply-on-4-7-x

#5638 chore: update gravitee node
  pom.xml
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5640 chore: upgrade account-linking dependency to use the right UserGatewa…
  pom.xml
Labels: apply-on-master

#5634 fix: exception error on mongo index creation
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
Labels: apply-on-4-7-x

#5635 fix: rework newsletter information
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/NewsletterResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/JerseySpringTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/NewsletterResourceTest.java
Labels: apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x

#5656 fix: remove the loginAttempt collection from migration scripts
  docs/upgrades/4.7.0/mariadb-migration.sh
  docs/upgrades/4.7.0/mongodb-migration.sh
  docs/upgrades/4.7.0/mysql-migration.sh
  docs/upgrades/4.7.0/postgres-migration.sh
  docs/upgrades/4.7.0/sqlserver-migration.sh
  docs/upgrades/4.7.0/sqlserver.schema
Labels: apply-on-master

#5646 AM-4885 saml2 plugin upgrade 4.3 4.4
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/SecureRandomString.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java
  pom.xml
Labels: apply-on-4-4-x

#5647 AM-4885 saml2 plugin upgrade 4.5 4.6 4.7 master
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/SecureRandomString.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#5639 chore: update gravitee node
  pom.xml
Labels: apply-on-4-4-x

#5664 AM-4890 AM-4892 plugin validation
  gravitee-am-ui/src/app/services/organization.service.ts
Labels: apply-on-master

#5670 fix: rollback to subscribe on index mongo creation
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
Labels: apply-on-master

#5673 Revert "fix: exception error on mongo index creation"
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
Labels: apply-on-master

#5665 fix: script to upgrade sql databases
  docs/upgrades/4.7.0/mariadb-migration.sh
  docs/upgrades/4.7.0/mysql-migration.sh
  docs/upgrades/4.7.0/postgres-migration.sh
  docs/upgrades/4.7.0/sqlserver-migration.sh
  docs/upgrades/4.7.0/sqlserver.schema
Labels: apply-on-4-7-x

#5632 fix: put validation on minLength and maxLength
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPoliciesResourceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/AbstractPasswordPolicy.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/passwordpolicy/CheckLength.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/passwordpolicy/PasswordPolicyCheckLengthValidator.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/passwordpolicy/PasswordPolicyCheckLengthValidatorTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5682 fix: added dynamic_user_groups for dataplane
  gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-13-dataplane-dynamic_user_groups-init.yml
  gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/dp-master.yml
Labels: apply-on-4-7-x

#5700 fix: test the need to dynamiGroup update and also test the identities…
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/pom.xml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Labels: apply-on-4-5-x

#5701 fix: test the need to dynamiGroup update and also test the identities…
  gravitee-am-dataplane/gravitee-am-dataplane-api/src/main/java/io/gravitee/am/dataplane/api/repository/UserRepository.java
  gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/repository/JdbcUserRepository.java
  gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/repository/model/JdbcUser.java
  gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/repository/spring/SpringDynamicUserGroupRepository.java
  gravitee-am-dataplane/gravitee-am-dataplane-test/src/test/java/io/gravitee/am/dataplane/api/repository/UserRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Labels: apply-on-master

#5606 fix: unable to select groups in group mapper in organization
  gravitee-am-ui/src/app/domain/settings/providers/provider/groups/groups/create/create.component.html
  gravitee-am-ui/src/app/domain/settings/providers/provider/groups/groups/groups.component.ts
  gravitee-am-ui/src/app/services/organization.service.ts
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5702 chore: bump account-linking in version 2.0.0
  pom.xml
Labels: apply-on-master

#5710 chore: update aws certificate plugin
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
  pom.xml
Labels: apply-on-master

#5715 AM-4868 max consecutive letters
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5714 AM-4870 jwt decoder issue
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/jwt/JWTServiceTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x

#5712 AM-4913 fix: added bidirectional relation for saml certificate
  gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.html
  gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#5717 fix: provide client secret on update/patch DCR response
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationServiceTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-3-x, apply-on-4-5-x, apply-on-4-7-x

#5735 fix: define the Nonce variable to be able to execute JS secured by CSP
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java
Labels: apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5736 fix: null idp in organization
  gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchOrganization.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/OrganizationServiceTest.java
  gravitee-am-ui/src/app/settings/management/general/general.component.html
  gravitee-am-ui/src/app/settings/management/general/general.component.ts
Labels: apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x
