Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-06, with the labels that each got.

#5935 fix: openapi spec for domain list
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DomainsResource.java
Labels: apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x

#5929 Feat/am 4928 JEST test redirect uri exp lan
  gravitee-am-test/api/management/apis/ApplicationApi.ts
  gravitee-am-test/api/management/apis/DomainApi.ts
  gravitee-am-test/api/management/apis/EmailApi.ts
  gravitee-am-test/api/management/apis/FormApi.ts
  gravitee-am-test/api/management/models/ClientRegistrationSettings.ts
  gravitee-am-test/api/management/models/NewEmail.ts
  gravitee-am-test/api/management/models/NewForm.ts
  gravitee-am-test/api/management/models/PatchClientRegistrationSettings.ts
  gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts
  gravitee-am-test/specs/gateway/redirect-uri-el.spec.ts
  gravitee-am-test/specs/management/applications.jest.spec.ts
Labels: apply-on-4-8-x

#5933 fix: r2dbc-mssql in 1.0.1+ version problem with cursoredExecution
  gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest_MSSQL.java
  gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/ConnectionFactoryProvider.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/MssqlR2DBCContainer.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#5957 AM-4737 aws cert version bumpup
  pom.xml
Labels: apply-on-master

#5960 fix: check presence of userInfo in the postLogout url
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/AbstractLogoutEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#5967 fix: redirect_uri without EL should not break application
  gravitee-am-service/src/main/java/io/gravitee/am/service/utils/EvaluableRedirectUri.java
  gravitee-am-test/specs/gateway/redirect-uri-el.spec.ts
Labels: apply-on-4-8-x

#5979 fix: validation of all the apps on enabling dynamic params
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DomainServiceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/domain/DomainValidatorImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/dynamicparams/ClientRedirectUrisValidator.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/validators/dynamicparams/ClientRegistrationSettingsValidator.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/DomainValidatorTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/dynamicparams/ClientRedirectUrisValidatorTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/validators/dynamicparams/ClientRegistrationSettingsValidatorTest.java
  gravitee-am-test/specs/management/applications.jest.spec.ts
Labels: apply-on-4-8-x

#5980 fix: evaluating query param without key
  gravitee-am-service/src/main/java/io/gravitee/am/service/utils/EvaluableRedirectUri.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/utils/EvaluableRedirectUriTest.java
  gravitee-am-test/specs/gateway/redirect-uri-el.spec.ts
  gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
Labels: apply-on-4-8-x

#5982 fix: messages rephrasing,
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
  gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html
  gravitee-am-ui/src/app/domain/applications/creation/steps/step2/step2.component.html
  gravitee-am-ui/src/app/domain/settings/openid/client-registration/settings/settings.component.html
Labels: apply-on-4-8-x

#5981 fix: for dynamic parameters ensure to remove the preceding ampersand
  gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
Labels: apply-on-4-8-x

#5988 fix: define preferCursorExecution option only for SQLServer
  gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/test/java/io/gravitee/am/dataplane/api/repository/test/AbstractTestRepositoryConfiguration.java
  gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/test/java/io/gravitee/am/dataplane/api/repository/test/JdbcDataPlaneTestConfiguration.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest.java
  gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/resources/container-license-acceptance.txt
  gravitee-am-reporter/gravitee-am-reporter-jdbc/src/test/java/io/gravitee/am/reporter/jdbc/audit/JdbcReporterJUnitConfiguration.java
  gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/ConnectionFactoryProvider.java
Labels: apply-on-4-7-x, apply-on-4-8-x

#5989 fix: define preferCursorExecution option only for SQLServer
  gravitee-am-reporter/gravitee-am-reporter-jdbc/src/test/java/io/gravitee/am/reporter/jdbc/audit/JdbcReporterJUnitConfiguration.java
  gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/ConnectionFactoryProvider.java
Labels: apply-on-4-6-x, apply-on-4-5-x

#6015 fix: manage to read additionalProperties for kafka notifier
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/notifications/KafkaNotifierConfigurationProvider.java
Labels: apply-on-4-8-x

#6018 AM-5255 fix: removing el dynamic params on overview page
  gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
Labels: apply-on-4-8-x

#5987 AM-5196 sanitize x headers
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/XForwardedHeadersSanitizer.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6040 AM-5268 fix: filtering application sensitive data in logs
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/management/ApplicationAuditBuilder.java
Labels: apply-on-master

#6046 fix(idp): add missing encode method with dedicated salt for PBKDF2 password encoder
  gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/PBKDF2PasswordEncoder.java
Labels: apply-on-4-8-x

#6049 ci(publish_rpm): fix release process to publish RPM with dryrun false
  .circleci/workflows.yml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6065 fix: revert the usage of Scheduler.computation for JWT signature
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#6079 chore: update FranceConnect to 3.1.1
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#6109 chore: addition of INFO log to know when Liquibase start
  gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/spring/AbstractRepositoryConfiguration.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/logback.xml
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/AbstractRepositoryConfiguration.java
Labels: apply-on-4-7-x, apply-on-4-8-x

#6124 fix: enable legacy.mongodb.regexCaseInsensitive by default to avoid b…
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractRepositoryConfiguration.java
Labels: apply-on-4-6-x
