Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-04, with the labels that each got.

#5745 fix: enable login button when autofill from password manager
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html
Labels: apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x

#5755 fix: when session is expired, error query parameters must contain errorHash
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/ErrorParamsUpdater.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CSRFHandlerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSRFHandlerTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-7-x

#5747 fix: upgrade gravitee-node and avoid error if Redis cache is unreachable
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserStoreImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserStoreImplV2.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/user/UserStoreTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/user/UserStoreV2Test.java
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#5694 AM-4882 fix: increased default socketTimeout for MANAGMENT mongodb client
  gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/java/io/gravitee/am/dataplane/mongodb/repository/MongoLoginAttemptRepository.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/provider/impl/MongoFactory.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
Labels: apply-on-master

#5746 AM-4855 ciba bad request
  gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProvider.java
  gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/test/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProviderTest.java
  gravitee-am-ciba-delegated-service/pom.xml
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestCallbackHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/AuthenticationRequestServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/ciba/service/AuthenticationRequestServiceTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5760 fix: use DomainBased dictionary outside of the common EmailService
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceImplTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/EmailService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EmailServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/VerifyAttemptServiceImpl.java
Labels: apply-on-master, apply-on-4-5-x, apply-on-4-7-x

#5773 fix: remove UserEnhancer from the userService to avoid SpringContext …
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/authentication/service/AuthenticationServiceTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/CommonUserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/OrganizationUserServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
Labels: apply-on-4-6-x

#5775 chore: upgraded libc6 in noble images
  docker/gateway/Dockerfile-dev-noble
  docker/gateway/Dockerfile-noble
  docker/management-api/Dockerfile-dev-noble
  docker/management-api/Dockerfile-noble
Labels: apply-on-4-6-x, apply-on-4-7-x

#5765 AM-4825 error message
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/AuditBuilder.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/AuthenticationAuditBuilder.java
  gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts
  postman/collections/graviteeio-am-user-management-collection-app-version.json
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5789 fix:assign users to groups from domain
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/GroupServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/GroupServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationMembersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationResourcesResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/MembersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/members/MembersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/MembersResourceTest.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcOrganizationUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringOrganizationUserRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringUserRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/OrganizationUserRepositoryTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/CommonUserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/MembershipService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/ResourceService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/GroupServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ResourceServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/GroupServiceTest.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ResourceServiceTest.java
  gravitee-am-test/specs/management/groups.jest.spec.ts
Labels: apply-on-4-6-x, apply-on-4-5-x

#5788 AM-4969 helm jdbc pool
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/api/configmap_repositories.yaml
  helm/tests/gateway/configmap_repositories.yaml
Labels: apply-on-4-6-x

#5792 fix: when CAS redirects to callback we should omit LoginCallbackOpenI…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandlerTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5817 fix: allow to filter the type of audits
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AuditServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/AuditServiceTest.java
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x

#5799 ci(rpm): Sign RPM with Gravitee GPG key
  .circleci/workflows.yml
Labels: apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x
