Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-02, with the labels that each got.

#5439 fix: always generate a new code for email factor
  gravitee-am-factor/gravitee-am-factor-email/src/main/java/io/gravitee/am/factor/email/provider/EmailFactorProvider.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5436 fix(mfa): avoid infinite loop if session expired
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandlerTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5440 fix: provide valid scope value to DeviceNotification service
  gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/pom.xml
  gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProvider.java
  gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/test/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProviderTest.java
Labels: apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5457 chore(deps): idp-ldap-plugin 2.1.2
  pom.xml
Labels: apply-on-master, apply-on-4-6-x

#5438 AM-4731 ext grant message
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/InvalidGrantException.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/ciba/CibaTokenGranter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/code/AuthorizationCodeTokenGranter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/refresh/RefreshTokenGranter.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/RevocationTokenEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/granter/code/AuthorizationCodeTokenGranterTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/granter/refresh/RefreshTokenGranterTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5472 fix: use the tid as seed to generate the moving factor
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummySession.java
  gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/transaction/TransactionHandler.java
  gravitee-am-test/specs/gateway/mfa.jest.spec.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5466 chore(openapi): Update Self-Account open api spec
  docs/self-service-account-api-descriptor.yml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5480 fix: regenerate the code only when there is not error in the URL
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpRequest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5485 chore(dep): upgrade gravitee BOM to 8.2.9
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountEndpointHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountWebAuthnCredentialsEndpointHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFARecoveryCodeEndpointTest.java
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5491 fix: changed dictionary provider for email service
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
Labels: apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5505 fix: removed default baseURL for loadPreAuthUserResource
  gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/resources/schemas/schema-form.json
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5506 chore(dep): upgrade gravitee bom to get netty in v4.1.118
  pom.xml
Labels: apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5517 fix(memory): stop services on undeploy domain
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/certificate/impl/CertificateManagerImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
Labels: apply-on-master, apply-on-4-5-x

#5524 chore(dep): upgrade json-smart to 2.5.2
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5498 fix: loop redirect on invalid form /resetPassword
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
Labels: apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5497 AM-4761 fix: validation of return_url param
  gravitee-am-common/src/main/java/io/gravitee/am/common/exception/oauth2/ReturnUrlMismatchException.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5548 AM-4794 userinfo redirect uri
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandlerTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidatorTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x
