Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-07, with the labels that each got.

#6146 fix: AM-5309 lift limit on users count
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/AbstractUsersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/OrganizationUsersResource.java
  gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#6158 fix: allow to add a new Android Key Root Certificate without overridi…
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/GraviteeWebAuthnOptions.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/attestation/GraviteeAndroidKeyAttestation.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/META-INF/services/io.vertx.ext.auth.webauthn.impl.attestation.Attestation
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6108 feat: retrieving auth code should remove it at the same time
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/code/AuthorizationCodeServiceTest.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/api/AuthorizationCodeRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MariadbHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MsSqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MySqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/PostgresqlHelper.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAuthorizationCodeRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/spring/SpringAuthorizationCodeRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAuthorizationCodeRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/AuthorizationCodeRepositoryTest.java
  gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#6202 chore: upgrade commons-lang3 to 3.18.0 & nimbus jose to 10.4
  gravitee-am-management-api/gravitee-am-management-api-rest/pom.xml
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#6220 fix: default constructor for RemoteJWKSourceResolver
  gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/jwt/jwks/remote/RemoteJWKSourceResolver.java
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6230 fix: prevent closing session if idToken is missing
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java
Labels: apply-on-master, apply-on-4-6-x, ready_to_test, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6219 chore: create docker image on github label.
  .circleci/workflows.yml
  .github/workflows/publish-images-for-test-env.yml
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x, build-docker-image

#6244 fix: AM-5434 purge service
  gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-purge/src/main/java/io/gravitee/am/management/services/purge/ScheduledPurgeService.java
Labels: apply-on-4-6-x

#6208 fix: map dynamic roles when account linking is used.
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6261 chore(ci): remove aqua from the CI
  .circleci/workflows.yml
Labels: apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x
