Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-08, with the labels that each got.

#6284 [AM-4985] Add support for escaping regex special characters in FilterCriteriaParser
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParser.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParserTest.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
  gravitee-am-ui/src/app/domain/settings/users/users.component.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#6282 fix: remove automatic assignment of default values for LDAP configura…
  gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6279 fix: AM-5233 global kafka reporter
  gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/common/event/Event.java
  gravitee-am-model/src/main/java/io/gravitee/am/model/common/event/EventKey.java
  gravitee-am-model/src/test/java/io/gravitee/am/model/common/event/EventKeyTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/vertx/EventBusReporterWrapper.java
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#6313 fix: AM-5462 Only register the certifcate for notifications if it has an expiry date
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainNotifierServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/DomainNotificationServiceTest.java
Labels: apply-on-master, apply-on-4-8-x

#6319 fix: prevent notification for certificates without expiry date
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateNotifierServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/CertificateNotifierServiceImplTest.java
Labels: apply-on-master

#6330 feat: add user to CIBA context
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestParametersHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequestResolver.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestParametersHandlerTest.java
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6375 fix: added idempotency policy param, to prevent edge case scenarios w…
  gravitee-am-model/src/main/java/io/gravitee/am/model/AuthenticationFlowContext.java
  gravitee-am-policy/gravitee-am-policy-enrich-auth-flow/src/main/java/io/gravitee/am/policy/enrich/auth/EnrichAuthFlowPolicy.java
  gravitee-am-policy/gravitee-am-policy-enrich-auth-flow/src/main/java/io/gravitee/am/policy/enrich/auth/configuration/EnrichAuthFlowPolicyConfiguration.java
  gravitee-am-policy/gravitee-am-policy-enrich-auth-flow/src/main/resources/schemas/schema-form.json
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/gateway/api/AuthenticationFlowContextRepository.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/gateway/api/JdbcAuthenticationFlowContextRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/gateway/MongoAuthenticationFlowContextRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/gateway/api/AuthenticationFlowContextRepositoryTest.java
Labels: apply-on-master, apply-on-4-8-x, build-docker-image

#6381 chore: update LDAP version
  pom.xml
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6376 fix: Use last identity to set source field on idp user
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#6383 AM55520 auth flow idem fix
  gravitee-am-policy/gravitee-am-policy-enrich-auth-flow/src/main/java/io/gravitee/am/policy/enrich/auth/EnrichAuthFlowPolicy.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/gateway/MongoAuthenticationFlowContextRepository.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AuthenticationFlowContextServiceImpl.java
Labels: apply-on-master, apply-on-4-8-x, build-docker-image
