Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-09, with the labels that each got.

#6407 fix: update LDAP version to fix connection pool
  pom.xml
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6422 AM-5510 update delete statement to support mssql
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringAccountAccessTokenRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/AccountAccessTokenRepositoryTest.java
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x

#6474 fix: missing port and host in helm charts
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
  helm/templates/common/_configmap-default-database.tpl
  helm/tests/common/configmap_database_test.yaml
Labels: apply-on-4-7-x, apply-on-4-8-x

#6507 AM-5143 fix: messages stopped being reported after some disables and enables
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/GraviteeContext.java
  gravitee-am-common/src/main/java/io/gravitee/am/common/utils/WriteStreamRegistry.java
  gravitee-am-common/src/test/java/io/gravitee/am/common/utils/WriteStreamRegistryTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/audit/impl/GatewayAuditReporterManager.java
  gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/KafkaReporterConfiguration.java
  gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/audit/KafkaAuditReporter.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/impl/AuditReporterVerticle.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/impl/ReportableHandlerLogger.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/vertx/EventBusReporterWrapper.java
Labels: apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#6505 AM-5599 rate limit expire reset
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/repository/ratelimit/model/RateLimit.java
  gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/ratelimit/api/JdbcRateLimitApiRepository.java
  gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/ratelimit/RateLimitObjectRepository.java
  gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/ratelimit/api/RateLimitRepositoryTest.java
Labels: apply-on-4-9-x

#6524 chore(dep): upgrade gravitee-bom in vesion 8.4.44
  pom.xml
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#6444 fix: Enhance idp plugin redeployment to avoid downtime
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java
Labels: apply-on-4-6-x, apply-on-4-5-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#6544 fix: AM-5585 retry drop mongodb indexes
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
Labels: apply-on-master

#6484 AM-5532 UriBuilderRequest filter default port in host header
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/StaticEnvironmentProvider.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/utils/StaticEnvironmentProviderTest.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequestTest.java
Labels: apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, build-docker-image, apply-on-4-9-x

#6561 fix: define port as null instead of empty string for default reporter…
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceTest.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/system/upgraders/DefaultReporterUpgraderTest.java
  gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
  gravitee-am-service/src/test/java/io/gravitee/am/service/ReporterServiceTest.java
Labels: apply-on-master, apply-on-4-8-x, apply-on-4-9-x

#6565 feat/AM-5686 helm sh chart label
  helm/templates/api/api-deployment.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/gateway/deployment_test.yaml
  helm/tests/ui/deployment_test.yaml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x
