Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-01, with the labels that each got.

#5302 AM-4591 introducing dataplane modules
  gravitee-am-dataplane/gravitee-am-dataplane-api/pom.xml
  gravitee-am-dataplane/gravitee-am-dataplane-api/src/main/java/io/gravitee/am/dataplane/api/DataPlane.java
  gravitee-am-dataplane/gravitee-am-dataplane-api/src/main/java/io/gravitee/am/dataplane/api/DataPlaneConfiguration.java
  gravitee-am-dataplane/gravitee-am-dataplane-api/src/main/java/io/gravitee/am/dataplane/api/DataPlaneDescription.java
  gravitee-am-dataplane/gravitee-am-dataplane-api/src/main/java/io/gravitee/am/dataplane/api/DataPlaneProvider.java
  gravitee-am-dataplane/gravitee-am-dataplane-mongodb/pom.xml
  gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/assembly/plugin-assembly.xml
  gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/java/io/gravitee/am/dataplane/mongodb/MongoDataPlane.java
  gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/java/io/gravitee/am/dataplane/mongodb/MongoDataPlaneConfiguration.java
  gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/java/io/gravitee/am/dataplane/mongodb/provider/MongoDataPlaneProvider.java
  gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/resources/plugin.properties
  gravitee-am-dataplane/pom.xml
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/pom.xml
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/node/GatewayNode.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
  gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/EmbeddedMongoConnectionProvider.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/node/ManagementNode.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/pom.xml
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/DataPlanePluginHandler.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/core/DataPlaneLoader.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/core/DataPlanePluginManager.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/core/MultiDataPlaneLoader.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/core/SingleDataPlaneLoader.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/spring/DataPlaneSpringConfiguration.java
  gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/resources/META-INF/spring.factories
  gravitee-am-plugins-handlers/pom.xml
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/provider/ClientWrapper.java
  gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/provider/ConnectionProvider.java
  gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/R2DBCConnectionProvider.java
  gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/R2DBCPoolWrapper.java
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/provider/impl/MongoClientWrapper.java
  gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/provider/impl/MongoConnectionProvider.java
  pom.xml
Labels: dataplane-split

#5311 fix: allow to create user with whitespace by default
  gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
Labels: apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5329 AM-4601 fix: unable to change anything on created reporter
  gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.html
  gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
Labels: apply-on-master, apply-on-4-6-x

#5328 AM-4601 fix: unable to change anything on created reporter 43 44
  gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.html
  gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
Labels: apply-on-4-3-x, apply-on-4-4-x

#5336 fix: unable to create file reporter
  gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5312 fix: correct display drop down list in table
  gravitee-am-ui/src/app/domain/alerts/general/general.component.scss
  gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/scopes/application-scopes.component.scss
  gravitee-am-ui/src/app/domain/components/memberships/memberships.component.scss
Labels: apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5348 AM-4615 fix upgrader for data-planes
  gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainServiceImpl.java
  gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DomainServiceTest.java
Labels: dataplane-split

#5356 fix: audit details when message is missing
  gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts
Labels: apply-on-4-6-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5367 chore: specify aws cli version
  .circleci/workflows.yml
Labels: apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5373 chore: fix circleci
  .circleci/workflows.yml
Labels: apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5379 chore: fix aws s3 from parameter
  .circleci/workflows.yml
Labels: apply-on-4-6-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-5-x

#5385 fix: Add Scopes dialog extension
  gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/scopes/application-scopes.component.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5393 chore: override dependencies waiting the BOM is up to date
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-4-x, apply-on-4-5-x

#5410 fix: remove GIS from the session on prompt=login
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java
Labels: apply-on-master, apply-on-4-6-x
