Repository gravitee-io/gravitee-access-management, pull requests merged in 2025-10, with the labels that each got.

#6625 test: AM-4843 jest test mobile app pkce
  gravitee-am-test/specs/gateway/fixtures/mobile-pkce-fixture.ts
  gravitee-am-test/specs/gateway/mobile-pkce-flow.jest.spec.ts
Labels: apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#6646 fix: use tokenRequest HttpResponse instead of generate a new one
  gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/token/TokenEndpoint.java
Labels: apply-on-4-9-x

#6651 AM-5459: set datasource as highest precedence in mongo provider
  gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoAbstractProvider.java
Labels: apply-on-master, apply-on-4-8-x, apply-on-4-9-x
